### ISSUE TITLE
Display predicted, actual cases + population on model pages

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#104]
## Technical
@lagerros is going to compile a fixed JSON indexed by Country, we place that as a file at GCS and render number in the similar way as we now do with the plot or did with countermeasures, or how done by @Mati-Roy [here](https://github.com/epidemics/covid/pull/160/files#diff-58cc30c2dfe9e8a85641965af7c25cfdR454).

Proper data from pipeline will be provided later.

Numbers are [1](https://github.com/epidemics/covid/pull/160#pullrequestreview-377117865):
* Confirmed
* Estimated true number*
* Population

with that note from the #160

## UX design
It should look similar to this one:
![image](https://user-images.githubusercontent.com/2741256/77095010-9e3ae380-6a0d-11ea-96b6-6a88173ca4df.png)

**Comment by jk3141** [comment]
It shouln't go to the sidebar, but above the graph on the country page (we had it in some  deisgn by Jan allready)

**Comment by hnykda** [comment]
I can't find it in the design, can you point to it here please: https://www.figma.com/file/4FTT6neJVlMD5CQHTTpprF/Covid-%5BWorkFile%5D?node-id=0%3A1

**Comment by hnykda** [comment]
And by `country pages` - you mean the `models` one?

**Comment by hnykda** [comment]
@gavento it's assigned to you, but I don't think you are going to do this, right?

**Comment by Matoo125** [comment]
what about this https://github.com/epidemics/covid/pull/160

**Comment by hnykda** [comment]
I think it's related, but I am not sure. Hence my clarifying questions above. Also #180 seems relevant.

**Comment by gavento** [comment]
I am working on the data for this (with Sualeh Asif), but only on the data part. I do not own the web part. Sorry about any confusion here, I am taking on #180 @hnykda

**Comment by hnykda** [comment]
Issue updated.

**Comment by wolverdude** [comment]
I just got this working, but I need to break for lunch. I pushed it to [this branch](https://github.com/epidemics/covid/tree/wolverdude/current-estimates), and it looks like this right now:

<img width="473" alt="Screen Shot 2020-03-19 at 12 20 10 PM" src="https://user-images.githubusercontent.com/4276302/77106277-0cff4900-69dc-11ea-9233-bc93a982cd76.png">

Obviously, it could use some styling work, but it updates properly. If anyone wants to mock it up or give feedback on the current appearance, please do so.

I'm also waiting on @epidemics/data to get me the live numbers.

**Comment by hnykda** [comment]
It looks good to me :+1:

**Comment by jk3141** [comment]
* as we don't have nowcasting yet, it should display the date for which the estimates are relevant
* displaying uncertainty estimates would be cool, but not if it is difficult to get from foretold

**Comment by wolverdude** [comment]
@jk3141 

> * as we don't have nowcasting yet, it should display the date for which the estimates are relevant

I've updated the PR to account for this.

> * displaying uncertainty estimates would be cool, but not if it is difficult to get from foretold

There's only the one `FT_Infected` number in the data. That said, there's also a `JH_Infected`, and I'm not sure what it means.

**Comment by wolverdude** [comment]
Ah, I see the live data has `FT_Infected_q05` and `FT_Infected_q95`. Yes, I can add in CI.

**Comment by wolverdude** [comment]
Still waiting on @hnykda or @gavento to upload the live data since neither @lagerros nor I have the privileges.

**Comment by wolverdude** [comment]
Here's the data, in case someone else has the privileges to upload it. The URLs should look like this when done:

`https://storage.googleapis.com/static-covid/static/data-{{CHANNEL}}-estimates-v1.json`

* https://epidemicforecasting.slack.com/files/UV6G09Z39/F010DBTEG4Q/data-main-estimates.json
* https://epidemicforecasting.slack.com/files/UV6G09Z39/F010F7U2FP1/data-staging-estimates.json
