### ISSUE TITLE
Fix filtering of country countermeasures

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#105]
Currently, it always shows just China.

![image](https://user-images.githubusercontent.com/2741256/76768703-ac81c900-679b-11ea-910c-55c2b38e2f01.png)

AC:
* when a country is selected, only countermeassures for the country are selected

**Comment by Bachibouzouk** [comment]
You can change it here to `None` https://github.com/epidemics/covid/blob/9cca928c95463b9fd4d2c5ce4f7a7c65c7e9d238/src/server/main.py#L114

What did not work was that I could not get the argument via the view (but the URL was working), I described the stand of my knowlegde before I went to bed ther : https://github.com/epidemics/covid/pull/88#issue-388892323

**Comment by hnykda** [comment]
Well, javascript is needed for that I am afraid (we should fetch data async on a change i.e. via different endpoint and update only that part of the site or fetch everything from frontend and filter it on frontend).

**Comment by hnykda** [comment]
Can you do it?

**Comment by Bachibouzouk** [comment]
I can do it, but I am much more fluent in python than js

**Comment by hnykda** [comment]
Same here... Would be great to get someone comfortable with JS

**Comment by Bachibouzouk** [comment]
And I am not sure I understand the order of the commands and how the d3 surcharge of the onchange affect the "normal" triggering of events

**Comment by Bachibouzouk** [comment]
With flask I know that using $.get from the template should provide a response to the template and can be done with jinja code. If no one else did it, I can do it in js with the `success` attribute of the $.get function

**Comment by hnykda** [comment]
Looking at the code, I don't think we have to mess with `d3`. We should listen `on_change` on this button: https://github.com/epidemics/covid/blob/master/src/server/templates/model.html#L69, based on which an ajax call on a new endpoint which can be e.g.:

```
async def get_countermeasures(request, country):
    return JsonResponse(...) 
```

and in JS it would be something like this I did in the past (**CAUTION! THIS MAY BE ENTIRELY WRONG, I HAVENT TESTED IT**):
```
$("#sidebar-with-data").on_change(function(e) {
    e.preventDefault();

    $.ajax({
        url: '/get_countermeasures',
        type: 'GET',
        contentType: 'application/json; charset=utf-8',
        data: {"country": "{COUNTRY}"},
           success: function(data)
           {
               $("#sidebar-with-data").html(data);
           }
     });
});
```

**Comment by Bachibouzouk** [comment]
The onchange method of the dropdown is overloaded [here](https://github.com/epidemics/covid/blob/552c94fa68855d32510436b062fb4395d22b2026/src/server/static/js/lines.js#L253) by the d3 code (this is why the function I had assigned to the onchange event didn't do anything, it was assigned once and immediately replaced by another onchange function by the d3 code)
