### ISSUE TITLE
Automatically and regularly load data from containment measures database

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#106]
@Bachibouzouk made [a PR](https://github.com/epidemics/covid/pull/88) for displaying containment measures from a .csv exported from [the Notion database of containment measures] on country pages

We ideally want this feeding of data to be automatic rather than manual; and to have it update whenever the Notion database updates. 

Notion doesn't have an API, but there's [an unofficial Python API wrapper](https://medium.com/@jamiealexandre/introducing-notion-py-an-unofficial-python-api-wrapper-for-notion-so-603700f92369)

This issue requires further speccing out for what's needed. This is just a reminder that it needs doing.

**Comment by Bachibouzouk** [comment]
The measures for each location can be found in this database: https://www.notion.so/977d5e5be0434bf996704ec361ad621d?v=aa8e0c75520a479ea48f56cb4c289b7e

Not yet implemented: parser from notion to pandas or csv

```
import os
import keyring


from notion.client import NotionClient

# Obtain the `token_v2` value by inspecting your browser cookies on a logged-in session on Notion.so
# I used keyring to save the token locally
token_v2 = keyring.get_password("notion", "token")
client = NotionClient(token_v2=token_v2)

cv = client.get_collection_view(
    "https://www.notion.so/977d5e5be0434bf996704ec361ad621d?v"
    "=aa8e0c75520a479ea48f56cb4c289b7e"
)
# here are the fields which interest us
# Country
# Description of measure implemented
# Keywords
# Source


# Run a filtered/sorted query using a view's default parameters
result = cv.default_query().execute()
for row in result:
    print(row.description_of_measure_implemented)
```


The containment measures could be in the sidebar with similar design as the previous one (one entry for each date, descending)

**Comment by Bachibouzouk** [comment]
One can use `row.description_of_measure_implemented` and `row.date_start.start`, the other ones are just in small caps.

Strategy: 
```
data = {
        "Country": [],
        "Description of measure implemented": [],
        "Keywords": [],
        "Source": [],
        "Date Start": []
}
```

The for each row fill the arrays, then create a DataFrame with `df=pd.DataFrame.from_dict(data)`
and insert that [here](https://github.com/epidemics/covid/blob/a3e9bffeaa2284d4cf64d7e8d7ce3f01fc80ef41/src/server/main.py#L60).

**Comment by Bachibouzouk** [comment]
I am AFK until tomorrow eve, if someone wants to implement this feel free!

**Comment by hnykda** [comment]
Looks like a good idea!

**Comment by hnykda** [comment]
FYI, I think that even if the sidebar is gone for now, the functionality is still wanted (i.e. the integration with notion)
