### ISSUE TITLE
Automatically and regularly run GLEaM simulations for different parameter settings

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#107]
Current parameter configurations are listed in [this Notion database](https://www.notion.so/12002dfa280a46748ac27cee1ff42bea?v=ec9d76c64cb9499899c8a160f328eb10). 

This is currently done by hand, and the files are then manually imported to the server. 

Ideally we'd find some kind of GLEaM API and be able to regularly run new simulations for all the different parameter configurations (as well as flexibly extending the number of configurations we want to run).

This needs further speccing out, but leaving this issue as a pointer

**Comment by gavento** [comment]
Note this is not possible with Gleam, @lagerros even contacter Gleam authors.
I have a semi-automated data pipeline in https://github.com/epidemics/epifor/, and I will hand it over to Anna Gajdova to run & publish the experiments on demand.

**Comment by gavento** [comment]
In large part resolved by the neat pipeline runner in https://github.com/epidemics/epifor/pull/10
It seems we won't get API from GLEAM (Jacob tried)
