### ISSUE TITLE
Brittle data handling in lines.js

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#117]
The JS code in https://github.com/epidemics/covid/blob/master/src/server/static/js/lines.js#L65 explicitely tests for `beta === "0.0"` etc, which breaks any other (valid) floating number encoding in the data (e.g. `0.00`, `0`). Can we make it more robust?

**Comment by Mati-Roy** [comment]
what about this?
`parseFloat(beta)===parseFloat("0.0")`

**Comment by wolverdude** [comment]
The offending line has been removed sometime in the interim, so this is no longer relevant.
