### ISSUE TITLE
describe the data

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#12]
To prevent that everyone is duplicating the data understanding, it would be nice to have a data description in the repository (data can be [download here](https://drive.google.com/open?id=19sVNHAOn_zNkYGsKsAmW_JW578zQcpLK)). That means that every data file(-type) should be described as:

* what the name of the datafile means (e.g. `cities/123-3.tsv` - is that a city with ID 123 from the `md_cities.tsv`? What's the suffix `-3`? - UPDATE: Jan Kulveit will tell us which is the correct one!) 
* what the specific datafile represents/stores (e.g. "modelled data for a specific region")
* what each column means (e.g. "`Median` means number of infected people", "`Timestep` corresponds to a day", ...)
* what datatypes are in the columns (string, category, int32, float64, ...)
* how to fix the data if there are any errors (partly done)
* how to load each dataset (partly done)

### Bonus
* automating what can be done (e.g. the data prep, or the loading)

## Hints
* [what "active cases" means in the `{area-type}/{filename}.tsv`](https://epidemicforecasting.slack.com/archives/CV3AQDVMM/p1583846958109100?thread_ts=1583836454.104000&cid=CV3AQDVMM) - `median` or maybe [this difference](https://epidemicforecasting.slack.com/archives/CV1CRTBGU/p1584009397109500?thread_ts=1583963342.098900&cid=CV1CRTBGU)?
* [Daniel's proposal](https://epidemicforecasting.slack.com/archives/CV3AQDVMM/p1583837261106000?thread_ts=1583836454.104000&cid=CV3AQDVMM)
* [from the call agenda](https://docs.google.com/document/d/1gKIeJUmPKgLxtWHub8AFYbFA2aJuqGMPWaSOKpjTOK0/edit#) - basically, we'll have e.g. 4 or up to 8 different versions of the same file, each corresponding to a different model

## AC
* there is a clear description of the available datasets in the [data-prep/README.md](https://github.com/epidemics/covid/tree/master/data-prep) and a way how to load them and work with them

**Comment by gavento** [comment]
There is a new tool to do the wrangling directly from GleamViz hdf5 files, see #29

**Comment by hnykda** [comment]
https://www.notion.so/Data-specs-b0a76e480f3c4eedacf7b9384ca3aa67#82bfb22bb192478481b602b0246950b9
