### ISSUE TITLE
Hospital line data provision

### ISSUE THREAD

**Issue by Mati-Roy** [epidemics/covid#125]
add hospital data into the [notion spec](https://www.notion.so/Data-specs-b0a76e480f3c4eedacf7b9384ca3aa67) (design it) and populate the data in the pipeline, upload them.

@gavento proposes [here](https://epidemicforecasting.slack.com/archives/CV0GGP151/p1584410272236900):

> The Y range should not be fixed at 0..200, since for many countries and scenarios much less than 20% of country pop will be infected at any moment. (E.g. 100k infected of 10M Czechs is a catastrophe but only goes to 10 on the chart?). I would vote for flexible domains?

@Jacob replies [here](https://epidemicforecasting.slack.com/archives/CV0GGP151/p1584410742237400?thread_ts=1584410272.236900&cid=CV0GGP151):
 
> I’m not a big fan of flexible domains; but your argument is compelling. Happy to do it for now.
> Maybe in future we could add a horizontal line for hospital capacity? Or some other contextualising measure? As long as we could actually get reliable data on it.

**Comment by Matoo125** [comment]
https://github.com/epidemics/covid/pull/137

**Comment by lagerros** [comment]
I collected data on critical care beds per 100k population in various countries https://www.notion.so/9db3df0271214655b13c17bb7565c40c?v=5e75cc3aed784a6baf42826304e7a923

**Comment by wolverdude** [comment]
Should it just show up as a horizontal line like this?

![image](https://user-images.githubusercontent.com/4276302/77034510-6ed19b80-6967-11ea-9af4-93e97ea0bf2d.png)

It seems like this feature in particular will make zoom/scroll more necessary. Where is that in the pipeline?

I'm signing off for the night now. I'll look deeper into this in the morning.

**Comment by lagerros** [comment]
Yes, it should just be a horizontal line. 

Zoom not currently in the pipeline; feel free to make an issue.

**Comment by wolverdude** [comment]
I think there's a piece of missing information here. The model is predicting _active_ cases, but it isn't predicting cases requiring hospitalization. Presumably, these will be many fewer, and for any decisions this chart would help people make, that is the actual quantity they're concerned about.

To put the hospital line on this chart as-is would be inviting them to compare apples to oranges.

**Comment by lagerros** [comment]
The amount of active cases requiring hospitalisation is an empirically measurable quantity (20% IIRC), as is the amount requiring oxygen treatment (5% IIRC) (rough guesses likely fine for reasons we discussed on call this morning). So if you have x critical care beds you can support x/5%=20x active cases.

More details on a similar guesstimate in the notion database.

**Comment by lagerros** [comment]
![Screenshot_20200320-230736](https://user-images.githubusercontent.com/21347592/77220667-b723c180-6aff-11ea-9737-be4ffe905270.png)

**Comment by hnykda** [comment]
related: https://github.com/epidemics/epifor/issues/1

**Comment by wolverdude** [comment]
@hnykda we can just not show the line when the data is null.

Perhaps we should also put some sort of modifier on the line since countries are expanding their critical care capacity?

**Comment by hnykda** [comment]
@gavento in the new pipeline you made, this is not present, right? (I made it part of https://github.com/epidemics/epifor/pull/8, but that's not part of the pipe).

**Comment by gavento** [comment]
@hnykda The main blocker is now the data itself - can someone data-savvy import it into the regions.yaml database, please?

Drawing plotly trace with single horizontal line is almost trivial.
We can also pass it in estimates or whereever (would not overthnink this, we may refactor into something later when we know more about our usage etc.)

**Comment by gavento** [comment]
Just noticed that #258 is a duplicate.

**Comment by hnykda** [comment]
I am closing this, done via #259

**Comment by hnykda** [comment]
followup #264
