### ISSUE TITLE
model visualization legend

### ISSUE THREAD

**Issue by Mati-Roy** [epidemics/covid#126]
@Jacobs says [here](https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1584419490129000):

> @Mati Roy I’d like to add a legend to the basic model visualisation. Should be doable in d3 quite easily.
> Showing it to some users, their reaction was “I don’t know what all the colored lines mean”.
> So I suggest we display some details about what the trajectories are. We’ll map the seasonality parameters {0.1, 0.7, 0.85} to {low seasonality, high seasonality, very high seasonality} and the air traffic parameters {0.2, 0.7} to {much reduced air traffic, slightly reduced air traffic}.
> @Jan Kulveit was keen not to include any simulation numbers that don’t make sense if you’re not familiar with gleam, so I hope changing from numbers to more vague verbal indications will work. But I expect Jan to have more opinions in the morning, and we’ll need some back and forth to figure out the right way of making the graphs more interpretable. Just treating this as a starting point for exploring options. (edited) 

@Jan K. says [here](https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1584430353129800?thread_ts=1584419490.129000&cid=CV1F9NB5K):

> I'm fine with the verbal descriptions
> I've checked with 2 user and you were right
> - are seasonality params really 0.1,0.7,0.85? should not be the case; we should have "no seasonality | weak seasonality | medium seasonality" (it's not strong)
>
> for param values (seasonality switched off or param setting 1; 0;85 ; 0.7
> for air traffic I'd call it "strong reduction in air travel|weak reduction in air travel"

**Comment by Mati-Roy** [comment]
I think those lines:
```
    row['Cumulative Median_s=0.85_at=0.2'], 
    row['Cumulative Median_s=0.7_at=0.7'], 
    row['Cumulative Median_s=0.1_at=0.2'],
    row['Cumulative Median_s=0.85_at=0.7'],
    row['Cumulative Median_s=0.1_at=0.7'],
    row['Cumulative Median_s=0.7_at=0.2'],
```
have those colors:
```
    var line1 = drawLine(1, '#753def')
    var line2 = drawLine(2, '#ef3d3d')
    var line3 = drawLine(3, '#ef993d')
    var line4 = drawLine(4, '#9edf5c')
    var line5 = drawLine(5, '#5cdfd3')
    var line6 = drawLine(6, '#cf5cdf')
```

**Comment by Mati-Roy** [comment]
x-post with Slack
> wait, I'm confused. param 1 means maximum seasonability, and 0 means none, right? given @Jan K says we want none, weak, and medium, should it be {0, 0.25, 0.5} ?

**Comment by lagerros** [comment]
Make sure that the legend is _always visible_, and not just on hover.

**Comment by Mati-Roy** [comment]
here's what I have:
![image](https://user-images.githubusercontent.com/5873950/76948941-2c17b100-68de-11ea-9995-5a71b132f38e.png)

**Comment by lagerros** [comment]
This has now been merged and is good enough for the mvp. 

Later enhancement will involve turning the chart into d3 and overlaying it on top of the graph rather than having it by the side.
