### ISSUE TITLE
Add case count and prediction to sidebar on "Models" page

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#144]
Above the "Containment measures" we want to display another section: 

...

CASE COUNT

**Confirmed: 180**
**Estimated true infections: 800 to 10000** (90% confidence)

(Updated March 15)

...

![image](https://user-images.githubusercontent.com/21347592/76911421-3601cb80-686e-11ea-99a8-08c3c5088115.png)

The confirmed number should be sourced from the John Hopkins/CSSE data, and the estimate should be based on Foretold data. The "Updated March 15" can be constant in the MVP. 

See [this repo](https://github.com/epidemics/epifor) for scripts for accessing the data.

**Comment by lagerros** [comment]
Related to : https://github.com/epidemics/covid/issues/104

**Comment by hnykda** [comment]
@gavento Do we have data for this in the pipeline so it can be fetched from FE? If not, can you please do it?

**Comment by Mati-Roy** [comment]
I've done the UI, but the data still need to be connected

![image](https://user-images.githubusercontent.com/5873950/76962647-fd0d3980-68f5-11ea-98be-22424a316395.png)

**Comment by hnykda** [comment]
I like it :+1: , good start

**Comment by hnykda** [comment]
Replaced by #104
