### ISSUE TITLE
display percentages on y-axis

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#146]
On the "Models" page.

![image](https://user-images.githubusercontent.com/21347592/76912965-dfe35700-6872-11ea-816c-574f541ab89e.png)

These should be formatted "0%" to "65%" rather than just "0" to "65".

It's unclear why this line in `lines.js` isn't working: 
![image](https://user-images.githubusercontent.com/21347592/76912913-b296a900-6872-11ea-9e1c-ae4d038e6982.png)

**Comment by wolverdude** [comment]
I should note it's not inherently clear what it's a percentage of. The entire country's population? We might want to include that in the axis label.

**Comment by lagerros** [comment]
Good point. Country population. Do include it!

**Comment by wolverdude** [comment]
So the current metric on the y-axis is *Active infections per 1000 people*. Should I transform that to percentages or just make the axis label accurate?

**Comment by wolverdude** [comment]
I'm going with the *Active infections per 1000 people* solution, since to do otherwise would require re-scaling not just the axis but all of the data as well.

**Comment by wolverdude** [comment]
@janpipek What exactly is the y-axis here?

**Comment by lagerros** [comment]
FYI Jan Kulveit (research lead) is not the same person as Jan Pipek.

**Comment by wolverdude** [comment]
Ah. I couldn't find another Github handle, so I assumed. Bad assumption. someone on @epidemics/data should know the answer to this though.

Data people: What is the precise meaning of the y-axis? It is currently labeled "Active infections", but Jan Kulveit said it actually represents "transitions". There's also some confusion as to whether it's scaled *per 1000 people* or *per 100 people*.

**Comment by gavento** [comment]
The data from the JSON is now per 1000 people. Not sure what gets displayed.

**Comment by lagerros** [comment]
Pinged Jan now hopefully he'll resolve this soon.

**Comment by wolverdude** [comment]
According to Jan, it is *New infections per day per 1000 people*
