### ISSUE TITLE
Make the graph on the "models" page full width

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#147]
Don't leave awkward spacing to the right between the graph and the "containment measures" sidebar

![image](https://user-images.githubusercontent.com/21347592/76913169-74e65000-6873-11ea-8dc9-90727acc27d4.png)

**Comment by wolverdude** [comment]
It's still messed up for me.

![Screen Shot 2020-03-18 at 9 27 10 AM](https://user-images.githubusercontent.com/4276302/76983564-dbfb1780-68fa-11ea-9346-1597f58adc00.png)
