### ISSUE TITLE
Add trajectory visualisation from models page to event-calculation results page

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#151]
This graph: 

![image](https://user-images.githubusercontent.com/21347592/76925018-54c78880-6895-11ea-8038-36e9ffad83af.png)

should be added here, in the location saying "caseGraph":

![image](https://user-images.githubusercontent.com/21347592/76925058-70cb2a00-6895-11ea-97b7-d9f438bd3359.png)

**Comment by Mati-Roy** [comment]
![image](https://user-images.githubusercontent.com/5873950/76956063-b0236600-68e9-11ea-9ca2-0828ef20671d.png)
