### ISSUE TITLE
Make countries appear in alphabetical order for country-selector in event decision tool

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#152]

**Comment by Mati-Roy** [comment]
AFAICT, it's already like this (?)
![image](https://user-images.githubusercontent.com/5873950/76956205-f8428880-68e9-11ea-929c-9f2aa0c25fb7.png)

**Comment by wolverdude** [comment]
It's still messed up for me.

![Screen Shot 2020-03-18 at 9 27 10 AM](https://user-images.githubusercontent.com/4276302/76983740-254b6700-68fb-11ea-8774-73017a2ebe7f.png)

**Comment by lagerros** [comment]
Mati what branch are you on?

On the [actual site](http://epidemicforecasting.org/request-event-evaluation) (master) it's still messed up for me.
