### ISSUE TITLE
Fix font awesome CDN load

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#156]
![image](https://user-images.githubusercontent.com/2741256/76940045-cf29f400-68f9-11ea-8c40-b09328e5d714.png)

Ac:
* font awesome loads without an error

**Comment by Bachibouzouk** [comment]
What I don't understand is that if I copy the link tag from https://cdnjs.com/libraries/font-awesome, it is exactly the same as we have ...

**Comment by hnykda** [comment]
Me neither, maybe @wolverdude or @jeromezng knows what's going on?

**Comment by Bachibouzouk** [comment]
There was the link twice, once with a bad integrity...
