### ISSUE TITLE
get a certificate and implement SSL

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#16]
We have ingress -  SSL certs can be somewhat easily added to the [ingress definition](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) (see `deploy/chart/templates...`). 

Ingress doesn't allow http redirects though, so we may have to:

1. keep http paths available too
2. set up https://www.starlette.io/middleware/#httpsredirectmiddleware so the app redirects http -> https

**Comment by gavento** [comment]
@hnykda can this be closed now that we have those certificates implemented?

**Comment by hnykda** [comment]
Do we?

**Comment by gavento** [comment]
Ah, sorry :man_facepalming:, I though kobzol resolved that ...

**Comment by gavento** [comment]
Note: if *you* take this up and any modification in DNS is needed (e.g. for LetsEncrypt), ping me.

**Comment by lunemec** [comment]
There is beta feature of automatic SSL via LetsEncrypt: https://cloud.google.com/run/docs/gke/auto-tls

I'm not certain if this is applicable here though.

**Comment by hnykda** [comment]
I just did https://github.com/epidemics/covid/pull/319 but then I got stuck

**Comment by jez4** [comment]
@hnykda I'm Trying to setup kubectl and I could not find it anywhere. I would like to follow SSL over LetsEncrypt which was proposed by @lunemec. What should I put in ~/.kube/config? :)

**Comment by lunemec** [comment]
@jez4 I think `.kube` folder is just a minikube config for local development.

If you want to update the cluster, you have to do it via terraform: https://github.com/epidemics/infra

**Comment by lunemec** [comment]
But first, take a look at what is the current k8s version, this beta feature is available only in very new versions.

**Comment by hnykda** [comment]
I think you are overthinking this. We already _have_ certificates in the cluster as secrets and the PR shows how to reference them. in ingress which works already. We don't need let's encrypt now.

What we need to make work is the communication between `Ingress` <-> `web-deployment` work with HTTP only somehow. E.g. django uses this: https://docs.djangoproject.com/en/3.0/ref/settings/#secure-proxy-ssl-header. 

This is our scenario:
> If your Django app is behind a proxy, though, the proxy may be “swallowing” whether the original request uses HTTPS or not. If there is a non-HTTPS connection between the proxy and Django then is_secure() would always return False – even for requests that were made via HTTPS by the end user. In contrast, if there is an HTTPS connection between the proxy and Django then is_secure() would always return True – even for requests that were made originally via HTTP.

I believe we want something similar but starlette (which is a server fastapi uses: https://www.starlette.io/middleware/#proxyheadersmiddleware)

I updated the branch but I am not sure if it's working, can't deploy now, github doesn't want to run actions :rage1: 
![image](https://user-images.githubusercontent.com/2741256/78297962-0838aa00-7531-11ea-87dd-3a57a885f23a.png)

**Comment by hnykda** [comment]
Merged.

**Comment by lunemec** [comment]
@hnykda did it work? It does not redirect me to https, and if I try https manually the certificate does not match. It does not match `epidemicsforecasting.org` because it is valid for `*.epidemicforecasting.org.` ...

and www. version is not there.
