### ISSUE TITLE
Countries should start with capital letter (otherwise "containment measures" breaks)

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#165]
See this page:

![image](https://user-images.githubusercontent.com/21347592/77007474-85550400-6921-11ea-80e6-b5cfb9122333.png)

For example, it should say "India" rather than "india". 

This was fine yesterday, but changed recently, I think due to #161 

Also, when we're using small capitals it breaks the integration with the "containment measures" database, c.f. #108 (The person who is working on that is @Bachibouzouk , who'll also be working on #106 later today)

**Comment by Bachibouzouk** [comment]
> Also, when we're using small capitals it breaks the integration with the "containment measures" database, c.f. #108 (The person who is working on that is @Bachibouzouk , who'll also be working on #106 later today)

We can perfectlu

**Comment by Bachibouzouk** [comment]
> Also, when we're using small capitals it breaks the integration with the "containment measures" database, c.f. #108 (The person who is working on that is @Bachibouzouk , who'll also be working on #106 later today)

Could we use country ISO (with 3 letters) for the values, that way we don't get in trouble with countries which might have different spelling or dash/no dash etc ?

**Comment by Matoo125** [comment]
Yes this broke with changed data source. I'm using object keys (that are lower case), instead of object[key].name  ... unfortunately my brain doesn't want to cooperate anymore. So I will go to sleep. It should be easy to fix.

**Comment by Bachibouzouk** [comment]
ISO3166-1Alpha3 in https://datahub.io/core/country-codes
Or Alpha3 in https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv

**Comment by Matoo125** [comment]
FE part solved by https://github.com/epidemics/covid/pull/181 .
