### ISSUE TITLE
Show the entire graph when user lands on home page

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#166]
Currently looks like: ![image](https://user-images.githubusercontent.com/21347592/77007678-dbc24280-6921-11ea-8feb-44008a9fafd5.png)

Instead, we want the user to: 
1) See the entire graph
2) See at least the top of text below, so they know there is more content if they scroll down

**Comment by wolverdude** [comment]
That should be a simple fix. I considered adding a `max-height` to it before but wasn't sure it was necessary. I'll do that tomorrow morning. Signing off for the night now.

**Comment by hnykda** [comment]
@lagerros Do we still wanted it given the sidebar is gone for now?

**Comment by wolverdude** [comment]
Even with the sidebar gone, the graph is still too tall for some screens.

**Comment by hnykda** [comment]
@lagerros Is this still relevant or is it good enough now?

**Comment by hnykda** [comment]
@lagerros is this still wanted?
