### ISSUE TITLE
Only x-axis (but not graph lines) extend to full-width

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#170]
The model used to go into 2021, but following #147 it only goes into fall of 2020: 

![image](https://user-images.githubusercontent.com/21347592/77011562-5c387180-6929-11ea-9644-4c8a1f8acb91.png)

**Comment by wolverdude** [comment]
The culprit here is actually #161. When they changed the data format, they included less data into the future. Still, the chart _should_ zoom the axis in response. I'll figure out how to get it to display right.

**Comment by lagerros** [comment]
@gavento @Matoo125 FYI that you removed some data with the new format.

Apart, from that, closed with #177 .
