### ISSUE TITLE
Compute and add more user friendly unit for y-axis

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#174]
This is not urgent, don't focus on it for the MVP, but it will be helpful later. 

Currently we are displaying "New infections per day per 1000 people"

A better unit would be "Active infections as a percentage of the population"

This could probably be computed from gleamviz data as "cumulative transitions into the infected bucket - cumulative transitions out of the infected bucket".

**Comment by gavento** [comment]
No, we **are** displaying "Active infections per 1000 people", that is the current meaning of the `infected_per_1000` data series in the JSON. (Converting to percentage is just /10)

I can add "New infections per 1000 people", "New recovered per 1000 people" or anything similar quite easily as additional series (same format) if you want. However, it doubles/multiplies the file size so I won't right now.

**Comment by Matoo125** [comment]
https://github.com/epidemics/covid/pull/186

**Comment by lagerros** [comment]
According to @jk3141 this is not what we're displaying. Rather we're displaying "transitions" in gleam, which correspond to the amount of people who get infected on a day (moving from susceptible to infected compartments)

**Comment by hnykda** [comment]
So should we change it to:

`New active infections per day as a percentage of population` @jk3141 ?

**Comment by hnykda** [comment]
According to @gavento , it's now right. Closing this
![image](https://user-images.githubusercontent.com/2741256/77187243-72cefc00-6ad4-11ea-8731-3d236f2bcf8a.png)


cc @jk3141

**Comment by jk3141** [comment]
The numbers are certainly not a % of the population.

**Comment by hnykda** [comment]
Which numbers. Are you aware of what transformations we do with the results from gleamviz?

**Comment by hnykda** [comment]
Until you give a reasoning for that, I am closing this.

**Comment by gavento** [comment]
The Y axis was wrong just ~15 mins ago, as were some labels. I fixed it in #218 @jk3141 

> According to @gavento , it's now right. Closing this

To be clear, I confirmed the meaning was "currently infected per 1000 pops", not that the displayed scale was right.

**Comment by gavento** [comment]
> The numbers are certainly not a % of the population.

I think that this can be interpreted in two ways: what is the meaning (active inf. / newly inf. / etc.) and whether it is in % (which it was not). @hnykda 

@jk3141, is it looking better now (have I missed something?)
