### ISSUE TITLE
Graph Y-label if factually wrong!

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#183]
It should read "Active infections per 1000 people", that is the semantics of the `infected_per_1000` data series in the JSON.

Related: #174 - While changing this, it should be easy to display the numbers as percentages (and divide them /10)

**Comment by Matoo125** [comment]
https://github.com/epidemics/covid/pull/186

**Comment by wolverdude** [comment]
See discussion on #146 for how the axis got labeled that way.
