### ISSUE TITLE
Quickfix: stop displyaing the countermeasures sidebar

### ISSUE THREAD

**Issue by jk3141** [epidemics/covid#187]
Stop displaying the Countermeasures sidebar, and reduce the page width to be in line with the header

Current implementation of the sidebar has multiple issues
- the dataset is incomplete
- the design of the sidebar is not really in line with the rest of the website - should be displayed bellow the predcitions
- better way how to display it would be to basically display the "labels" from notion and have the text descriptions only as a hover box 

before we fix them, it's better to not display it at all

**Comment by jk3141** [comment]
also the sidebar does not refresh when changing the country

**Comment by hnykda** [comment]
> also the sidebar does not refresh when changing the country
It does for me as expected (when clicking on different countries, I get different results). I suspect some adblocker or extension on your side.

**Comment by hnykda** [comment]
@jk3141 like this?
![image](https://user-images.githubusercontent.com/2741256/77069211-45a51f80-69e8-11ea-8492-14e2ac366893.png)

Also, where should we display info about the model if we want to have countermeasures below (it would be _really_ long page if we just stuck it under)?

**Comment by hnykda** [comment]
Related discussion: https://epidemicforecasting.slack.com/archives/CV0GGP151/p1584621683296700?thread_ts=1584611114.274300&cid=CV0GGP151.

Followup #191 

Solved by #190
