### ISSUE TITLE
Display countermeasures (below?) model

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#191]
Next steps of https://github.com/epidemics/covid/issues/187.

* the design of the sidebar is not really in line with the rest of the website - should be displayed bellow the predcitions
* better way how to display it would be to basically display the "labels" from notion and have the text descriptions only as a hover box

**Comment by hnykda** [comment]
Will probably clash with #106 (@Bachibouzouk I think you can "temporarily" test it below the model or even keep it as is)

**Comment by hnykda** [comment]
Wait with this one please.

**Comment by Bachibouzouk** [comment]
Just need to add 
```
      <hr />
      <div id="containment_measures">
        <!-- filled with a js script from static/js/lines.js -->
      </div>
      <hr />
```
the last paragraph of the central column

**Comment by hnykda** [comment]
@jk3141 Is this true: https://github.com/epidemics/covid/pull/176#issuecomment-601350089 then? Should we just display it below? Under all that text about the model?

**Comment by lagerros** [comment]
Closing this since it is being replaced by #193
