### ISSUE TITLE
Temporal visualisation of containment measures

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#193]
Blocked by #251

We want to add countermeasures to the historical graph now in a similar manner:
![image](https://user-images.githubusercontent.com/2741256/77472404-278a5580-6e14-11ea-8eba-cff0af202417.png)

We'll want to combine some nowcasting + official historical data to add a _second_ graph to the "model" page, which shows the timeline in a particular country up to that point. 

On this timeline we also want to display the various containment measures that were taken, as sourced from the database. 

In particular, to add the labels of the measure (e.g. "event cancellation", "travel ban") below the particular date on the x-axis when they were implemented. 

This will likely take some intense UX work to get into a good shape. 

It will need more speccing out, but just leaving it here as a reminder so it doesn't get lost.

**Comment by hnykda** [comment]
Thanks, it's bigger, as it needs some data wrangling too.

**Comment by jk3141** [comment]
![IMG_20200321_234141](https://user-images.githubusercontent.com/38469878/77238073-5b237080-6bc5-11ea-9272-d97b205c04d6.jpg) possible visualisation of most important meaaures

**Comment by hnykda** [comment]
By @lagerros :

> @Daniel Hnyk I think you misunderstood re #193 — we don’t need any estimates of severity to visualise containment measures. A basic version is just to have a label (e.g. “travel ban”) appear under the relevant date on the graph.
Attached is a simple example (though there are some design changes I’d make to the real one, e.g. having different colored labels corresponding to different type of measure (as in Notion), and having them below instead of on top of graph, and showing how far across time they extend)
(Then, later, we might want to add other visualisations for the database, but that’s a separate thing)

**Comment by hnykda** [comment]
@gavento We technically have the data as part of the `estimates` data part. We could visualize it as separate traces on the charts with containment measures fetched from a different data source.

**Comment by wolverdude** [comment]
I think #251 should be part of the same chart as the forecasts, but we can re-use that data in this separate chart. I also think this chart should be logarithmically scaled.

**Comment by mathijshenquet** [comment]
> UI for interventions original plan. There are few basic types, upon click, more of the hierarchy is displayed
<sub>[View in Slack](https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1585433693062100)</sub>

**Comment by mathijshenquet** [comment]
@hnykda Can we add the containment measures to data-main-v3.json?

**Comment by hnykda** [comment]
Sure. There are IMO two options:

* put it in the data-mian-v3.json, which would make the JSON potentially somewhat bigger but I guess till reasonable (AFAIK the dataset has a few hundreds KB)
* have an endpoint which would fetch the CSV on the backend from notion (we have code for that already, could be probably tweaked a bit, we removed that as [it wasn't use](https://github.com/epidemics/covid/pull/250/files#diff-f63e43f3fade3c182108d73f67a99b2dL1)), so you would get it by something like `GET /get-countermeasures/{country}` and backend woud return it

Should I just do it?

**Comment by mathijshenquet** [comment]
2 sounds good to me. That would be great!

**Comment by hnykda** [comment]
So as can be seen here: https://github.com/epidemics/epifor/blob/2d90b55235d859ed9055e7f5c726875406021933/notebooks/containments/containment-to-json.ipynb. In that notebook you can see the structure and how it was done in the case you needed to rerun it. Only `pandas` is required. 

It's accessible in https://storage.googleapis.com/static-covid/static/data-main-containments.json. 

The biggest "problem": it's currently indexed under ISO alpha 3 codes - will you be able to match it to the selection?

**Comment by mathijshenquet** [comment]
@hnykda there is a problem around column 8284 `"keywords": NaN, `

**Comment by hnykda** [comment]
Damn... Fixed, uploaded

**Comment by hazarane** [comment]
Replaced by #477
