### ISSUE TITLE
Pre-select location based on user location

### ISSUE THREAD

**Issue by Mati-Roy** [epidemics/covid#206]
Basically improving this https://github.com/epidemics/covid/blob/master/src/server/static/js/lines.js#L10 based on something like https://stackoverflow.com/questions/3489460/how-to-get-visitors-location-i-e-country-using-geolocation

**Comment by Mati-Roy** [comment]
Maybe we could also pre-fill the mitigation strength field if we already know it

**Comment by mathijshenquet** [comment]
I think that geoguessing by IP would be a possible GDPR violation. I suggests we use the Language-Accept instead.

**Comment by wolverdude** [comment]
Based on cursory research, I think this should be fine since we aren't storing the IP address and connecting it to other personal data.

> the Regional Court of Berlin (the "Kammergericht") ruled that IP addresses in the hands of website operators could qualify as personal data if the relevant individual provides additional details to the website operator (e.g., name, email address, etc.) in the course of using the website

[Source](https://www.whitecase.com/publications/alert/court-confirms-ip-addresses-are-personal-data-some-cases)

**Comment by wolverdude** [comment]
Note that website analytics tools can still dereference IPs and tell you where your traffic is coming from, and we'd be using that data just as anonymously as they are.

> "Location data is not always personal data," said Fabinger. "It highly depends on the context and the use case. The same data set can be privacy-neutral when used for asset tracking as part of logistics optimization services and privacy sensitive when used for tracking of a child or patients in a hospital."

[Source](https://iapp.org/news/a/what-the-gdpr-will-mean-for-companies-tracking-location/)
