### ISSUE TITLE
Oxford logo 

### ISSUE THREAD

**Issue by jk3141** [epidemics/covid#208]
We should have the Oxford in the footer

**Comment by lagerros** [comment]
In addition, add logos for [gleamviz](https://www.google.com/search?q=gleamviz+logo&sxsrf=ALeKk01CAmJY8U6gJUuIbyTrYN0biugCNw:1584732219399&source=lnms&tbm=isch&sa=X&ved=2ahUKEwja9oDI46noAhVLMawKHQ8GDmMQ_AUoAXoECAwQAw&biw=1527&bih=854#imgrc=EFxF-DqmmKf2pM) 

And [Australian National University](https://www.google.com/search?q=australian+national+university+logo&sxsrf=ALeKk03AoNLwNSXozTcbOMbKSCdhJGKjfg:1584732181885&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjrpY-246noAhUIRa0KHRZUDHkQ_AUoAXoECA8QAw&biw=1527&bih=854)

**Comment by OAGr** [comment]
Foretold:
If on dark background:
https://www.foretold.io/logowhite.4cbd279a.png

Light background:
https://www.dropbox.com/s/wf39xazvu7kjued/foretold-light-logo.png?dl=0
