### ISSUE TITLE
name mitigation timeseries naturally

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#219]
Currently, the generated data are having indices of timeseries such as `"COVID seasonality 0.85, Air traffic 0.70"`, causing issues at the frontend when trying to decode what it means.

The model _needs_ to define this better, explicitly stating what each mitigation means, i.e. basically providing this mapping already (so it doesn't have to happen at frontend): https://github.com/epidemics/covid/blob/2cf9b945d80851f96dbd92f105f57f471d4f126f/src/server/static/js/lines.js#L5-L24. 

UPDATE: It's already in[ the config](https://github.com/epidemics/epifor/blob/master/config.yaml#L39-L40), so it may be just enough to fix it in the code: https://github.com/epidemics/epifor/blob/master/process_h5s.py#L43.

Data notion spec just to be  sure: https://www.notion.so/Data-specs-b0a76e480f3c4eedacf7b9384ca3aa67

Followup card: #220

**Comment by svecon** [comment]
Not sure what exactly is meant here, as the frontend already has a "natural" label. Is this Issue about explaining what exactly WEAK/MEDIUM/STRONG mean?

**Comment by hnykda** [comment]
The parameters may change and we are recomputing it quite often. There is no reason why this shouldn't be done upstream and we have already introduced three bugs with this.

**Comment by hnykda** [comment]
@gavento

**Comment by gavento** [comment]
The color is also specified in [the data-pipeline config](https://github.com/epidemics/epifor/blob/master/config.yaml#L39-L40), however, the JSON format currently does not have a place to put it, so a minor spec change is required.

**Comment by gavento** [comment]
Resolved by https://github.com/epidemics/epifor/pull/10 (by saving Plotly traces) and #248 (in JS)
