### ISSUE TITLE
Automate the web export of data with case counts and estimates

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#221]
Currently, the data are manually inputted just for a few countries: https://storage.googleapis.com/static-covid/static/data-main-estimates-v1.json.

Automate it for our countries (or a selection). See [notion case spec](https://www.notion.so/Data-specs-b0a76e480f3c4eedacf7b9384ca3aa67).

**Comment by hnykda** [comment]
See related #195

**Comment by gavento** [comment]
**First,** we ca do it only for the countries in Foretold. This may be straightforward, including confidence intervals (the full distribution is in `FTPred`).

Use https://github.com/epidemics/epifor/blob/master/epifor/data/export.py to create the overall JSON structure, see https://www.notion.so/Data-specs-b0a76e480f3c4eedacf7b9384ca3aa67 for the spec.

**Later,** we can compute this for any region by summing the estimated sub-regions in `region.est['est_active']`. (Confidence interval combination may be trickier, though, but we can also just omit it.)

**Comment by gavento** [comment]
Resolved by https://github.com/epidemics/epifor/pull/10 (the quality still varies, though, but is fine with manual overrides in config)
