### ISSUE TITLE
Setup start of yaxis 

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#222]
Charting follow up for #118 (this issue is blocked by #118 ).

**Comment by gavento** [comment]
@hnykda I am confused - why do we need this at the frontend? I would say the Y axis should always start at 0. Rationale: especially if it is the case that the # of infected never goes below e.g. 1 per 1000, we want people to see this in the graph too.

**Comment by hnykda** [comment]
The error is therefor more likely on my side - I thought that gleamviz data are not "offsetted", based on https://github.com/epidemics/covid/issues/118#issue-582714474 . If it's fixed at the backend, than all good and please close thisone

**Comment by gavento** [comment]
Gleamviz data is not offsetted, but the pipeline offsets them. (#232 could improve it but the heuristic is likely good enough & roubust for now.)
