### ISSUE TITLE
add aditional countries

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#225]
Currently, we display just a few countries, but we could extend that data to more countries as we have them.

Get a list of new countries and extend our data pipeline by that.

hint: https://github.com/epidemics/epifor/blob/master/config.yaml#L53

**Comment by gavento** [comment]
The keys for countries can be found in https://github.com/epidemics/epifor/blob/master/data/regions.yaml

**Comment by gavento** [comment]
May require #230 if we add many new countries (for latency / data volume).

**Comment by hnykda** [comment]
So if I understand correctly, to extend to other countries, we should make somewhat sure that there have been enough foretold predictions for that region, right (https://www.foretold.io/c/1dd5b83a-075c-4c9f-b896-3172ec899f26?state=open)

**Comment by lagerros** [comment]
@jk3141 how granular do we want to go here?

Gleamviz would obviously allow us to display all the way down to individual cities in most countries. Here's how deep it goes for Czech Republic: 
![image](https://user-images.githubusercontent.com/21347592/77261026-af236900-6c48-11ea-84aa-f68816e49c12.png)

**Comment by gavento** [comment]
Resolved by https://github.com/epidemics/epifor/pull/10
* Country graphs are loaded independently
* Default setting is ~90 countries
