### ISSUE TITLE
use data for hospital view in the chart

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#226]
Display the line at the model graph

blocked by Data task: #125 
Epic: #223

**Comment by gavento** [comment]
Adding a plotly trace with single horizontal line into the current plot is almost trivial.
We can also pass it in estimates or whereever (would not overthnink this, we may refactor into something later when we know more about our usage etc.)

**Comment by wolverdude** [comment]
I was confused and thought that #125 was this task. I had some data @hnykda had put together before, so I created a PR (#259) that loads this and displays it on the chart when available. It should be easy to switch the data source when it becomes available.

**Comment by gavento** [comment]
Nice; and I think whatever works ... :+1:
