### ISSUE TITLE
Add plot of the cummulative "infected" or "recovered" people (or a stacked-plot of the 4 compartments)

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#227]
To better show the progress of the epidemic, we could display the graph of
* the total (cummulative) number of people ever infected and recovered (in %)
* a stacked plot of the currently occupied compartments (Susceptible (initially almost everyone), Exposed, Infectious, Recovered, summing to 100%)

This has 2 parts:
* Export to JSON: should be relatively straightforward - we already have the commulative&new transitions data while creating the JSON. 
  * It would make it larger, though.
* Add the plot to the web.
  * This may not be difficult in Plotly, even stacked (see [the docs](https://plot.ly/javascript/filled-area-plots/#stacked-area-chart)).
  * Needs design. E.g. stacked can't be displayed for more scenarios at once.

@jk3141 Design? Is this useful?

@lagerros @Bachibouzouk

**Comment by Bachibouzouk** [comment]
@gavento, just to make sure, you are talking about displaying simulated number, not the tallied ones, right?

**Comment by gavento** [comment]
Yes, the simulated ones.

(I would hope the tallied numbers to never be above few percent ...)

**Comment by lagerros** [comment]
I think it would be too intense to add a visualisation of this to the one plot currently on site (since there will be other things, #193 and #125 ), so think we should just focus on displaying the summary statistics as stated in #192 

Eventually we'll also want to show the total death count.

**Comment by gavento** [comment]
i will close this for now as it is unwanted and there is no action to take.
