### ISSUE TITLE
Refactor infected estimations from Foretold and Region code

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#228]
Helper methods for estimating infected pops in subregions is currenty scattered in the classes `FTData` (e.g. [here](https://github.com/epidemics/epifor/blob/master/epifor/data/foretold.py#L111)) and `Regions` (e.g. [here](https://github.com/epidemics/epifor/blob/master/epifor/regions.py#L200)).

It would be better to factorize the entire estimation algorithm to their own file and class. (It would also allow adding new, independent estimation algorithms).

**Comment by gavento** [comment]
@jez4 @hnykda

**Comment by hnykda** [comment]
Is this still relevant?

**Comment by hnykda** [comment]
Closing this as it was mostly for epifor and this has been redone in epimodel https://github.com/epidemics/epimodel/pull/25
