### ISSUE TITLE
Improve loading Jonh Hopkins (CSSE) data for dates

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#233]
Only the last day is currently loaded from the CSSE data. We should
* Load all days, properly loading the dates (US format?). Required for series export in #221 
* Select the day closest to `start_date` from the pipeline config (if we simulate from a past point, e.g. to verify the models).

**Note:** We need to preserve the nmbers to be monotone non-decreasing. Some of the last numbers are sometimes 0 (meaning missing data? we don't care at this point), they must be adjusted to be non-decreasing.

@jez4

**Comment by gavento** [comment]
Todo: direct loading from github. E.g. from Dan:
```
from urllib.request import urlopen
result = urlopen('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv').read()
```

**Comment by gavento** [comment]
Todo: check and update for the new file naming/format CSSE announced just today. 

See https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by jez4** [comment]
Selection of the nearest day is done. Date is taken from config.

**Comment by hnykda** [comment]
Cool. So do we have the historical data for the Deaths/Confirmed in the output JSONs?

**Comment by jez4** [comment]
Ok. Output JSON is not having this, yet. Thx for direction :)

**Comment by hnykda** [comment]
Yeah, I think we currently have only the latest day in the output JSON, e.g. in https://storage.googleapis.com/static-covid/static/data-ttest5-v3.json:
![image](https://user-images.githubusercontent.com/2741256/77473793-412c9c80-6e16-11ea-8d6c-7edefbf804cf.png)

But It's pretty weird format to put it there just for each day as a map/dict :thinking: . A regular "timeseries" storage (in lists) would be much better, similarly to what is currently used for each country data: https://storage.googleapis.com/static-covid/static/batch-2020-03-24T18-19-34.832424+01-00-jan2-fixpops/lines-traces-senegal.json. 

WDYT? 

cc @gavento

**Comment by jez4** [comment]
I will have to create definition.xml in the format which gleamviz will understand, right? Is there any standard, which specifies how to store the dates in it?

**Comment by hnykda** [comment]
I think these data will not have to go through gleamviz (it's just exporting them from CSSE and somehow getting them in the JSON), so I don't think you have to. But it needs the changes in the pipeline which Tomas may have some thoughts on.

**Comment by jez4** [comment]
I reached the fce propagate_down. I have historical data for 'Active'. Do you have any advice how to continue?

**Comment by hnykda** [comment]
Not really, I don't understand the code yet - are you able to dig down to find out how to add it to the final generated JSONs? Maybe @gavento has some tips.

**Comment by gavento** [comment]
> Yeah, I think we currently have only the latest day in the output JSON, e.g. in https://storage.googleapis.com/static-covid/static/data-ttest5-v3.json:
> But It's pretty weird format to put it there just for each day as a map/dict thinking . A regular "timeseries" storage (in lists) would be much better, similarly to what is currently used for each country data: https://storage.googleapis.com/static-covid/static/batch-2020-03-24T18-19-34.832424+01-00-jan2-fixpops/lines-traces-senegal.json.

The point here was to have something easily viewable on the web and I thought this may be easier in JS, but either is fine with me :man_shrugging: 

The only use of series I thought of was for a graph, but for that I would prefer to just include more Plotly traces directly (also in the per-country file, fits there easily) rather that the raw data in series to be processed.

**Comment by gavento** [comment]
@jez4 Apologies about the propagating down part - this needs a refactor for a while, and I did not expect you to need to go there. I am happy to patch it if you have changed the API (a good thing to do too, probably).

**Comment by mathijshenquet** [comment]
Have you looked at [ECDC][1] as data source? 

Pro's:
* Argument from authority: [Our world in Data][2] explicitly chose them over CSSE.
* They only post an entry if they actually have data, you can do some interpolation in between if you want
* They only have country level data and the data is much more regular. For example Chinese data goes back further (if I remember right).

Con's:
* They don't have 'recovered'
* They only have country level data
* (minor) data is in delta's

I personally also use this instead of CSSE data.

[1]: https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide
[2]: https://ourworldindata.org/coronavirus#our-world-in-data-relies-on-data-from-the-european-cdc

**Comment by jez4** [comment]
@hnykda @gavento  I have managed to get the historical data into the output json. Right now I have to solve 'hong kong city' which is not accumulated.

**Comment by hnykda** [comment]
Can you ignore Honk Kong for now just so we get the data to unblock the other cards? 

Is the PR ready to be reviewed so we can merge it then?

**Comment by jez4** [comment]
@hnykda I have merged the branch.

**Comment by hnykda** [comment]
Cool, let's close it then.
