### ISSUE TITLE
Make latest gleamviz XML files available on site, and link to them from landing page

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#238]
We want it to be possible for users to replicate/extend our analyses.

**Comment by hnykda** [comment]
@gavento could you please add it to the pipeline script upload phase and link it here: https://github.com/epidemics/covid/blob/master/src/server/templates/about.html#L81 ?

**Comment by gavento** [comment]
Done in https://github.com/epidemics/epifor/pull/10, waits for the merge of #248 
Closed bu #248

**Comment by gavento** [comment]
Updated About links and text
