### ISSUE TITLE
Extend the graph further in time

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#240]
Based on [user feedback](https://www.notion.so/William-Saunders-93a9d12369064d4b83c50eb96cc87b54) -- "cutting it off at end of year can give a false sense of security, e.g. not visualising potential of secondary outbreaks next year". 

Previously the graph took in more data, but for some reason this changed with the introduction of the new data format in #161 

People working on data/data-formats: 
@Matoo125 @jez4 @gavento 

The gleamviz maximum is 365 days. So let's do that instead of the current 250 days.

**Comment by gavento** [comment]
* Anna is running the simulations (not on github, please ask her on Slac). It should be just a simulation setting in Gleam.
* The further in future, the less certain, so it may be a strategic decision. @jk3141 what do you say?

**Comment by gavento** [comment]
New online data computed for 350 days.
