### ISSUE TITLE
make COVID mitigation dataset meta-info publicly access

### ISSUE THREAD

**Issue by Nora-Ammann** [epidemics/covid#241]
- On the website: "This is work in progress: check the completion state of various countries [here](https://www.notion.so/dbf0f4ffc03f4417a16d65a6d08eea69?v=845ef4baafd44e72b9c483381b90caae) (we hope to have comprehensive coverage on Sun).

- However, if I click on "here", I get: "You do not have access to Epidemic forecasting. Please contact an admin to add you as a member."Is this on purpose?

**Comment by lagerros** [comment]
Thanks, this has been fixed now
