### ISSUE TITLE
make it easier to download COVID  mitigation dateset

### ISSUE THREAD

**Issue by Nora-Ammann** [epidemics/covid#242]
- current explanation: > To download the data as a .csv file; make a copy of this page, and then click "Export".

- This took me a while to understand. I suggest rephrasing to: To download the data as a .csv file; make a copy of this page (click "Duplicate" in the top right corner), and then click "Export".

**Comment by lagerros** [comment]
Fixed (for future notion edits like these, feel free to just go ahead and make them without submitting an issue)
