### ISSUE TITLE
Improve Facebook sharing view of page

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#246]
Currently looks like: 

![image](https://user-images.githubusercontent.com/21347592/77371832-70151680-6d21-11ea-82ca-9aa6706d96ed.png)

Instead we want: 

* A screenshot showing our main model and the Oxford logo. I made some to the right dimensions, available in Notion [here](https://www.notion.so/Site-thumbnail-60cbc9e23fe945bfae936083b0550f73)
* The title should not be "model", but instead "Medium-term COVID-19 forecast"

**Comment by wolverdude** [comment]
Here's what I'm using for the `description` meta tag, which will appear as the site summary in search results and shares:

> Researchers from the Oxford Future of Humanity Institute have created country-specific predictions of the current and future spread of the COVID-19 coronavirus pandemic using GLEAMviz epidemic modeling software and a database of mitigation and control measures in effect around the world.

I tried to include as many relevant keywords as I could for SEO purposes. Please let me know if/how I should tweak it. Also, what is this organization called? I currently have the `author` set as:

> Epidemic Forecasting

**Comment by wolverdude** [comment]
I ended up dropping the `author` meta tag, since it doesn't seem to be necessary.
