### ISSUE TITLE
add channel arg flexibility in the data fetching for casemap

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#254]
Add the same functionality with `channel` as is in the line graph [here](https://github.com/epidemics/covid/blob/master/src/server/static/js/lines.js#L11)

**Comment by gavento** [comment]
Changed the URL to main (as I just added the ISO codes to the pipeline).

Having the URL channel param would still be nice for testing.

**Comment by hnykda** [comment]
So far there hasn't been a request for this, so closing.
