### ISSUE TITLE
[Low priority] Redesign region storage to allow more attributes etc.

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#257]
Discussion issue about the data format for our dataset. Feel free to collect ideas. However, I would focus on the goals, and I assign this a low priority. (Although I would love to spend days discussing designs, formats and their merits ;-) )

Note that the region Yaml has some advantages:
* Can be inspected and fixed by hand (I did this so many times, including the hierarchy itself)
* Can be meaningfully kept in version control
* Easy lo load and interpret for others (but not any standard)
But also disadvantages
* One fixed hierarchy (while in reality there are overlaps) instead of a DAG
* For some algs. would use flat structure slightly better
* Part of the current API is messy
* Time series would bloat it up (loss of readability)
* Note that speed is and will be fine for long time (unless we add many time series?)

Another reason for existence of this issue is as a magnet for this topic, please keep it here :)

**Comment by gavento** [comment]
Misc notes to self:

The region data we want to keep has two parts:
* Fixed data (single instance)
  * Names, ids, populations, gleam kind and id, relationships, locs, ISOa3, IANA, hosp/ICU beds, others?
  * Relationships are the only structured data, all else is a table
    * Some of the relationships would be better modeled through a DAG (middle east vs africa) but that is not clear. And this may bring further problems (how to properly sum children regions if they overlap further below)
  * We may need our own "kind" separate from gleamviz
    * make gleamviz kind part of the gleamviz ID? e.g. `kind:gleam_id`
  * Te only reason we have cities/basins is for GLEAM (and maybe few notable cities?), so focus on countries and provinces/states
* Variable data
  * JH data, Jan's estimates, Foretold estimates, 
  * Derived quantities? (E.g. simulation stats - maxima, minima, etc)

* Nice to have: Some kind of versioning / diff viewability for fixed data

* Keys: Hierarchical or flat?
  * country ISO, province&state ISO, continent ISO, IANA for basin?
    * are these unique?
  * special: World, EU, middle east

**Comment by hnykda** [comment]
@gavento is this still relevant?

**Comment by hnykda** [comment]
Closing via https://github.com/epidemics/epimodel/pull/25, as most of that has been done already. There are things left which I hope we can break down into smaller items.
