### ISSUE TITLE
Add hospital & ICU beds to our region data set

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#258]
Import hospital beds and ICU numbers to the relevant tags in `data/regions.yaml`. 
(there is even a snippet doing something similar)

Note this is not about the format itself (see #259)
Also note some country/state/other name ambiguities (e.g. Georgia)

@hnykda @jez4 Do you already have something quick to do it?

@lagerros Do we have the data?

**Comment by lagerros** [comment]
Data: https://www.notion.so/9db3df0271214655b13c17bb7565c40c?v=5e75cc3aed784a6baf42826304e7a923

Though I think @wolverdude is working on the frontend for this, and already has access to the data, and might be about to push something soon?

So I'm not sure if there's been some confusion, please check this slack thread: https://epidemicforecasting.slack.com/archives/CV93A58G7/p1584957939023200

**Comment by gavento** [comment]
@wolverdude I think the graph part is trivial in plotly pipleine side once we have the data (just another trace in the JSONs; to prevent duplication). The text information in text must be JS, I guess ..

**Comment by hnykda** [comment]
This is currently done via https://github.com/epidemics/covid/issues/226 and related cards, but it's using old, manually created data from https://github.com/epidemics/epifor/pull/8/. That's what @wolverdude used now in #259 .

So this task is about adding data properly to the pipeline. (it's mostly just a single CSV). I really just downloaded that notion dataset in CSV and appended to my data.

Frontend needs to be updated in that case then (not to take it from the currently manually wrangled data but from the pipeline outputs).

**Comment by hnykda** [comment]
Should be done in a similar way to #253

**Comment by gavento** [comment]
Just in case it helps, this is the one-time code I used for the ISOs:
```python
rs=epifor.Regions.load_from_yaml('data/regions.yaml')
with open('all.json') as f: isos=json.load(f)
for i in isos: 
    r = rs.find_names(i['name'], kinds='country') 
    if len(r) != 1:
        print("not a unique match", i, r)
        continue
    r[0].iso_alpha_3 = i['alpha-3']
with open('data/regions-2.yaml', 'wt') as f: rs.write_yaml(f)
```

**Comment by veselatereza** [comment]
thanks!

**Comment by hnykda** [comment]
Additional (newer?) data available at https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1585258897031300?thread_ts=1585234929.020700&cid=CV1F9NB5K (but hopefully shouldn't change much the pipeline)

**Comment by mathijshenquet** [comment]
I have a age distribution data and expected hospitalization, critical and fatality rates for various countries. I can export them as CSV in whatever way would be most convenient (anything from Mathematica essentially).
[rates.txt](https://github.com/epidemics/covid/files/4390182/rates.txt)
[agedata.txt](https://github.com/epidemics/covid/files/4390183/agedata.txt)

**Comment by veselatereza** [comment]
@gavento we thought with Daniel to then include the resulting number b*f/c to the regions.yaml? Do you think that is ok? Or have we misunderstood what needs to be done?

**Comment by gavento** [comment]
Some number should be included there, I think. Which one is up to you, I guess :)

(Haing it as external CSV is also fine, but needs syncing on names ...)

**Comment by gavento** [comment]
(Apologies for not having built a better codebase for this type of work :sweat: )

**Comment by veselatereza** [comment]
@gavento @hnykda I have prepared manually the data for the "maximal percentage of population that can be infected so that ICU beds are still avalable" (not sure how to name it :D). 
The data is ready for all the 59 countries found in https://www.notion.so/9db3df0271214655b13c17bb7565c40c?v=5e75cc3aed784a6baf42826304e7a923, I have it in a csv so far.
I can put it in the regions.yaml in the corresponding `country` block, and then add the code so that it propagates in the json, should I do it?
(I can put there all the 59 countries except Andorra (which is not there), Dubai (it is in the `regions.yaml` as a city, should I add it to the city?) and Hong Kong (it is in the `regions.yaml` as a state, should I add it there?).
Thanks!

**Comment by hnykda** [comment]
AFAIK done in epifor/#15
