### ISSUE TITLE
Some graphs don't have hospital line despite being in the database

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#261]
e.g. Sweden is in the Notion database but doesn't have a line: 
![image](https://user-images.githubusercontent.com/21347592/77494776-df633700-6e03-11ea-98ee-0571d2bab189.png)

#259

**Comment by hnykda** [comment]
IMO the reason for it was that Sweden wasn't part of the original country selection, only for which I put the data for (manually, via https://github.com/epidemics/epifor/pull/8/). 

In the meantime, Tomas extended the country selection and Sweden is one of them.

Proper fix is #258

**Comment by hnykda** [comment]
Fixed in https://github.com/epidemics/epimodel/pull/25 (so should be visible as soon as we do #296
