### ISSUE TITLE
Global mitigation strength: don't make the 'details' optionally pop in/out but leave them out for good

### ISSUE THREAD

**Issue by Nora-Ammann** [epidemics/covid#269]
however, this section can be deleted to make it shorter

> The available mitigation levels are:

    None: Do nothing
    Weak: Decrease of effective transmission rate by 20%
    Moderate: Decrease of effective transmission rate by 50%
    Strong: Decrease of effective transmission rate by 80%

**Comment by lagerros** [comment]
I'm not a fan of this, since it will make it much harder to use the site as a dashboard where you get a good overview of multiple facts/numbers. I also want the main graph to be visible as soon as the user lands on the site, which will be harder if there's more description text.

**Comment by hnykda** [comment]
Closed via #315
