### ISSUE TITLE
add a second graph displaying 'cumulative infection numbers' below the 'active infections' graph

### ISSUE THREAD

**Issue by Nora-Ammann** [epidemics/covid#271]

**Comment by gavento** [comment]
Thanks for creating the issue!
Before I try to assign this: I think the consensus 1-2 days ago was that this would be too cluttered, did this change?
CC @jk3141 @lagerros

**Comment by lagerros** [comment]
No it didn't change, I'd prefer to stick to a table displaying these numbers for now, as mentioned in #192
