### ISSUE TITLE
model: turn the lines into error bars (?)

### ISSUE THREAD

**Issue by Nora-Ammann** [epidemics/covid#279]
I'm not sure what this would imply and how easy/difficult that is - but I think it would be pretty valuable to do in order to _communicate uncertainty_ (currently the arbitrarily precise predictions suggest more certainty than we have).

**Comment by mathijshenquet** [comment]
Frontend-wise we can easily do this.

**Comment by hnykda** [comment]
We have the stats represented as CI now. So closing this.
