### ISSUE TITLE
Downloaded graphs should have (the option for a) non-inverted color scheme

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#283]
You probably want people to download the graph so that they can put it in documents. Then there should be an option, probably by default, to download with non-inverted color scheme. People are not going to print a solid black graph or figure out how to fix this.

Related to: #282

**Comment by hnykda** [comment]
It's unfortunately not possible to somehow change the export functionality, but we could set the background of the plot to transparent, which doesn't really change much (as it's set to the same color as the rest of the page):
![image](https://user-images.githubusercontent.com/2741256/77821769-0c0d9c00-70ed-11ea-8638-30134a6463ae.png)

and then it would export _without_ background, but that would mean that in png it looks like this:
![image](https://user-images.githubusercontent.com/2741256/77821787-25164d00-70ed-11ea-8efc-e0ae3ae891b7.png)

which they still can't put anywhere very reliably as e.g. axis won't be visible on a white background.

I think it would have to go with the #282 if decided.

**Comment by mathijshenquet** [comment]
I think we can make a custom download handler ([link][1]) and then redraw the plot off screen with different settings.

[1]:https://stackoverflow.com/a/45105871
