### ISSUE TITLE
UX: Remember when user closes the "We offer consuting" bar

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#286]
The yellow bar offering consulting seems rather intrusive into the design (by design, I guess), but if closed, reappears with every reload, which is sort of annoying.
It would be possible to somehow remember that it was closed and not show it again (at least for a while). At least my experience would improve ;) 
A design question for @jk3141 @lagerros 

One technical solution would be to use something like `localStorage.setItem` and `localStorage.getItem`. Storing a time of the closing would allow us to redisplay e.g. every 1-2 days. (if the banner has a new message, we can just bump the localStorage key)

**Comment by mathijshenquet** [comment]
I used `sessionStorage` to be conservative, this is reset for every new window/tab. Do you think this is ok?
