### ISSUE TITLE
transformation pipeline for new data

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#29]
* there are some steps to wrangle the [data already](https://github.com/epidemics/covid/tree/master/data-prep)
* we want to be able to have a nice single pipeline out of it, which would output a file with all relevant data needed for the plots (the smaller, the better, of course). Could be e.g. HDF with multiple datasets in it.
* the data inside should be ideally fully self-described, i.e. that single HDF would also include metadata such as "when the modelled was generated" or "what parameters correspond to what column"
* ideally, it work with the deployment easily (currently via [initContainers](https://github.com/epidemics/covid/blob/master/deploy/chart/templates/deployment-charts.yaml#L35), also mentioned [in point 1](https://epidemicforecasting.slack.com/archives/CV1CRTBGU/p1584049336160800)), 
* There is also related #12 task

Bonus points for making it automated, but that can come in a followup task.

Relevant discussions:
* next set of data should be available today https://epidemicforecasting.slack.com/archives/CV93A58G7/p1584087032011600 (13.03.2020)
* validation of [the data prep for visualization](https://epidemicforecasting.slack.com/archives/CV93A58G7/p1584087392013700)

AC:
* when new modelled data arrive, it's at maximum few commands away (possibly including redeploy) from being able to update it at the size

**Comment by hnykda** [comment]
cc @hrosspet who worked on the last bit and have a better idea how the data should look like.

**Comment by gavento** [comment]
I implemented another data import directly from Gleam HDF5: https://github.com/epidemics/covid/blob/data_pipeline/data-prep/process_data_hdf.py
Run it as `python process_data_hdf.py ~/GLEAMviz/data/sims/*.gvh5` but ONLY works if you give it exactly the 24 parameter settings we are currently processing.

The model parameters are determined from the `definition.xml` files in the `*.gvh5` directories - naming no longer matters.

The output CSV format (v2?) seems super messy. The header column order is also different (for the value columns). Another format would also allow combining any runs with any params.

**Comment by gavento** [comment]
I think this got resolved over time, and there is a major update to the pipeline in https://github.com/epidemics/epifor/pull/10. New data are processed ~every day. Closing.
