### ISSUE TITLE
Add correct R0 numbers to the frontend

### ISSUE THREAD

**Issue by Discordius** [epidemics/covid#301]
As part of the UI Rework PR (#300) we now have short explanations of what the different mitigation strengths mean in terms of reducing R0. Those numbers are currently random guesses and should definitely not be merged to master, and should instead be dynamically updated with our changes to the model. 

![Screen Shot 2020-03-29 at 9 01 39 PM](https://user-images.githubusercontent.com/9090789/77874770-e5da2000-7202-11ea-93a3-0078aa8fdcb5.png)

See the above screenshot for the places where we currently talk implicitly about R0.

**Comment by Discordius** [comment]
This is the current blocker for #315

**Comment by lagerros** [comment]
Feedback from Jan: 
 
> I like the UI, like the reduction as percents. The intuitive explanations are likely hiding too much complexity. Maybe if add some footnote that the numbers are for illustration only and
> -some people can infect dozens of others
> -the estimates are illustrative, based on a specific choice of R0 and serial interval
> 
> Jan Kulveit  (there is some right balance between informing the public and not annoying experts, not sure about where exactly it is)

**Comment by gavento** [comment]
@Discordius I would not go for dynamic updates of the parameters - we never updated beta and I do not expect to do it more than 0-2 times over the next 2 months. Updating the mitigation strengths already requires manual UI update (e.g. the percentages).

The model parameters we are using are beta=1.285 and mu=0.5 (exp. 2 day infectious period), you may want to confirm R0 with Jan.

**Comment by lagerros** [comment]
Solved by a recent commit.
