### ISSUE TITLE
[TRACKING] Decrease data size and latency on slow connections

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#309]
## Current data sizes

The data we serve is growing quite a bit lately, slowing some clients on slower lines.

* The `data-main-v3.json` is 1.2MB
  * Most of this is currently taken by JH data history (lot of repeated keys)
* All the per-country graph data is 70MB (170x ~500kB)
  * This has been already optimized a bit (not repeating all dates in plots, limit precision to ~3 digits)

### Restructure the JH data

Omit repeating tags, store one array per tag and assume the days are consecutive. Limiting float precision not applicable (integers).

### Compress 

The data compresses very well: `data-main-v3.json` gzipped has 94kB (~8%), country lines data compressed has 20MB (~120kB / country)

* Can we setup transparent HTTP compression in GCS, @hnykda? `curl -H "Accept-Encoding: gzip" https://storage.googleapis.com/static-covid/static/data-main-v3.json` shows no transport compression. 
* As last resort, we could compress on export and decompress in JS - does that make sense?

### Use other formats

* BSON does not help with the main file at all (labels are still repeated)
* HDF5 would be great for any numerical/time series data, but would need a larger overhaul of, JS and still require a main JSON file?
  * There is a promising [pure-JS reader lib](https://github.com/usnistgov/jsfive)

**Comment by gavento** [comment]
Re GCS gzip encoding: https://cloud.google.com/storage/docs/transcoding
@jez4 would you be interested in taking it on? As I understand it, needs compression and setting headers before upload.
Also, it would be good to research which browsers may not support `Content-encoding: gzip` (hopefully none).

**Comment by hnykda** [comment]
> Can we setup transparent HTTP compression in GCS, @hnykda? curl -H "Accept-Encoding: gzip" https://storage.googleapis.com/static-covid/static/data-main-v3.json shows no transport compression.

It's turned on by default as soon as we use `-Z` switch. Solved via: https://github.com/epidemics/epifor/pull/20

**Comment by hnykda** [comment]
FYI I don't think we should do much more now, i.e. this is a very low hanging fruit and we are on few KBs already, which will likely not get us much further now...
