### ISSUE TITLE
be strict about deployment branch names

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#31]
Currently not only `master` gets deployed to production, but every branch which has `master`... So e.g. a branch called `do-not-ever-push-to-master` will make it straight into production

Same is true for `staging`. (because in the github actions steps I  am using `contains(github.ref, "master")`, and not just `github.ref == "master"` or whatever should be there)

**Comment by hnykda** [comment]
Thanks!

**Comment by jez4** [comment]
@lunemec Hello, could you advise with the testing of github actions. I have a task with github actions and I would like to avoid the mess by pushing to repo, while testing github actions.

**Comment by hnykda** [comment]
@jez4 I think that you can just open your branch and do your changes there, commenting out all the stuff you don't want to be run.

**Comment by lunemec** [comment]
@jez4 as @hnykda says, I created a fake step, but added condition there specifically for my branch so I could test the condition works. But you won't be able to test deployment like that for example.

**Comment by jez4** [comment]
yes. I need to upload something to bucket. that should be ok 
Thank you
