### ISSUE TITLE
Make sure Google Analytics works even when the rest of the javascript crashes

### ISSUE THREAD

**Issue by Discordius** [epidemics/covid#311]
I haven't looked into how we initialize GA, but depending on how we do it, having broken javascript can prevent GA from sending events, which can cause pretty serious prioritization issues in browser-support

**Comment by hnykda** [comment]
How can we effectively test this? I.e. what are the AC?

**Comment by Discordius** [comment]
I would use something like [browserstack](https://www.browserstack.com/) to get access to old browsers, and then make sure that the browser you are using still sends GA events, even when the main site is broken and the javascript is crashing.

**Comment by mathijshenquet** [comment]
I verified that it currently works on ie7.
