### ISSUE TITLE
(Tiny) Update copy

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#316]
Few copy requests. Mentioning high-performance computers and flight network is something which may be good for uninformed public but is a red flag for epi modelling professionals
https://www.notion.so/Wiki-and-documents-81b1d50642d44151acb38f0f0ec69a09?p=8ca9118f5d8c40358ee5d9bbb7bf2277&showMoveTo=true

**Comment by mathijshenquet** [comment]
Does this copy need to be finished still?

**Comment by hnykda** [comment]
I believe so given it's so recent.
