### ISSUE TITLE
Fix the automatic country selection

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#323]
Suspected regression of https://github.com/epidemics/covid/issues/312 .

When I load the page now, I can see that until everything renders, there is: `czechia` (correct), but a second later it's overwritten by `United Kingdom`.

**Comment by mathijshenquet** [comment]
I think I know why this happens. Its because the key of czechia is czech+republic. The proper way to fix this would be to use ISO3 codes as country identifiers everywhere.

**Comment by hnykda** [comment]
Note that if we go to the city granularity, we can't use ISO 3 :-( ...

**Comment by mathijshenquet** [comment]
How about https://www.unece.org/cefact/locode/service/location.html

**Comment by hnykda** [comment]
These are ISO alpha 2, how would that help us? :thinking: 

We already tried to add ISO alpha 3 where possible, see https://github.com/epidemics/epifor/blob/master/data/regions.yaml for countries. But as you may have noticed, users would like e.g. cities which we don't have it.
