### ISSUE TITLE
Longterm fix for preselection of location

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#336]
Follow up for https://github.com/epidemics/covid/issues/323, as the fix doesn't make it work for `USA`. 

The fix for CZ was done by this: https://github.com/epidemics/covid/pull/324/files.

**Comment by hnykda** [comment]
@mathijshenquet Would you be so kind and specify what where/what was your proposal, e.g. even if we had ISO alpha 3 (where?), what would have to be done.

**Comment by wolverdude** [comment]
From the San Francisco Bay area, this still defaults to `United Kingdom` for me.

**Comment by mathijshenquet** [comment]
The basic issue is that the timezone detection code does not know which keys are assigned to which country. I.e. it can recognize the county but then does not know which keys to use. I don't know where the mapping from countries to keys is defined, probably somewhere in `epifor`. If I had this it would be an easy fix.

**Comment by hnykda** [comment]
Yes, it's in https://github.com/epidemics/epifor/blob/master/data/regions.yaml which I referenced in the previous issue: https://github.com/epidemics/covid/issues/323#issuecomment-607278529

Note that Tomas is working on redesigning this entirely in the new epimodel repo.

**Comment by mathijshenquet** [comment]
Blocked by #350

**Comment by mathijshenquet** [comment]
Timezones have been added to epimodel data https://github.com/epidemics/epimodel-covid-data/blob/master/timezones.csv after this is exposed to the frontend we can fix this issue.

**Comment by hnykda** [comment]
@mathijshenquet can you update me if the timezones are being used already by new FE (and https://github.com/epidemics/epimodel/pull/25)? If yes, we can close this and if not, we should unblock it (as the data are there)

**Comment by mathijshenquet** [comment]
It fixed!
