### ISSUE TITLE
Design breaks if I double click on the legend

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#337]
If you double click a line in the legend it gets isolated in the plot. 

However, this causes the design to break, see screenshot.

![image](https://user-images.githubusercontent.com/21347592/78292970-b7976180-74dc-11ea-8f78-b3d9b0919122.png)

**Comment by mathijshenquet** [comment]
The chart also brakes if you enable/disable some of the traces. The `makeReactive` function should be attached like this: `plotlyGraph.on('ploty_redraw', makeReactive)`.

**Comment by mathijshenquet** [comment]
For me the scaling is also off. In portrait the graph is too low DPI:
![image](https://user-images.githubusercontent.com/242143/78303133-628b3800-753c-11ea-9f23-01d8a747eef9.png)

But in horizontal orientation it is to high DPI:
![image](https://user-images.githubusercontent.com/242143/78303112-5901d000-753c-11ea-8f59-019fa32efae0.png)

**Comment by mathijshenquet** [comment]
This looks better for me: `const CHART_WIDTH = Math.max(500, Math.min(1000, CHART_CONTAINER.clientWidth));`.

**Comment by wolverdude** [comment]
It looks like the double-click functionality re-adds width/height to the Plotly svg elements.

From #314 regarding the solution I implemented:

> I have to modify the HTML elements Plotly creates to do it, which could break unexpectedly if they have unanticipated hooks, but I'll do my best to QA it.

This is one of those "unanticipated hooks". I didn't know about the double-click functionality at the time.

**Comment by mathijshenquet** [comment]
Did you see my suggestion? The `plotyly_redraw` event should do the right thing. After intialization by for example `newPlot` you can attach it to the dom element by `.on(cb)`
