### ISSUE TITLE
switch bucket to multiregional

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#338]
Partly prepared here: https://github.com/epidemics/infra/pull/1

The goal is to have bucket multiregional instead of just regional (`storage_class = "STANDARD"`). Multiregional bucket have lower latency when accessed from different locations.

We can't have a downtime, so recommended approach:

1. create new multiregional bucket (see the infra PR above)
2. use google transfer to transfer data from the current bucket to the new regional one (https://console.cloud.google.com/transfer/cloud?project=epidemics-270907)
3. switch the STATIC_URL to this new bucket URL
4. deploy the application with this new static_url, validate it works (staging, then production)

5. delete and create again the same bucket as we had now `static-covid` with MULTI_REGIONAL and switch the STATIC_URL back to this, so all scripts and stuff depending on this don't break...

**Comment by hnykda** [comment]
@lunemec any chance you would like to try this one (can give you perms for infra)? :eyes:

**Comment by lunemec** [comment]
@hnykda yeah, sure. But it will increase cluster costs.

**Comment by lunemec** [comment]
@hnykda can I start? I'm not sure if I can apply those terraform, and I think I'll need google cloud permissions to copy the buckets.

**Comment by hnykda** [comment]
Hey, sorry, got in the middle of stuff. Could you give me your gmail account I can add to our org? Also, do you want to do it via terraform?

**Comment by lunemec** [comment]
@hnykda `lu.nemec@gmail.com`

Yes, I'll do it via terraform.

**Comment by hnykda** [comment]
You are an editor now: https://github.com/epidemics/infra/commit/4190ca8db86685d3cd75c783cac0c612a2144532#diff-0eb4ca96c71300b689450168777e0279R22

**Comment by hnykda** [comment]
Sorry, it's already multiregional, it's my bad not checking it earlier and not catching that up when specifying the task...
