### ISSUE TITLE
get credits/money for the project infrustructure

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#34]
We currently have 300$ and it seems that we burn maybe like 50$/day. But k8s will start to be 72$/month just for the node, therefore we may need to get more money...

Some rough calculation and maybe cluster optimization could be considered.

Related #35

**Comment by lunemec** [comment]
@hnykda you can set-up your k8s nodes to be preemptible, that is way cheaper, but will cause nodes to be restarted unscheduled at random. If this is simple website that can tolerate it, it should not be a problem.
I looked in charts but I don't see it there. This will be in the k8s cluster settings.
Also reducing number of nodes, and correctly configuring cpu/memory requests/limits in the charts can help.

**Comment by hnykda** [comment]
Hey, thanks Lukas for suggestions. I have actually used preemptible nodes already: https://github.com/epidemics/infra/blob/master/gke.tf#L73 .

**Comment by gavento** [comment]
While getting explicit infrastructure funding should be on our roadmap, I would hope this not to be a problem:
* Most of the processing moved to the browser (D3 loading data from static files - hosting those is very cheap up to 1M views / day)
* We could just ask google for credit? It is obviously for a good cause; they only give us resources if it gets very popular; we could display acknowledgement. (Still is quite some work to do.)
* As a last-resort costs cover, I would pledge up to $1000 if we actually get so many visitors.

**Comment by lunemec** [comment]
@hnykda what is the current estimated monthly cost for k8s cluster? I know it changes based on usage, so it will most likely increase, but just a ballpark number?

Few ideas what can help: ~changing the datacenter: `us-west1-c` - different DCs have different prices.~ Nope `us-west1` is the cheapest option.

Still 3x nodes per `$7.30` per month is not that much, but ingress for example is pretty expensive.

Maybe consider `f1-micro` or `g1-small`, but from experience, they have too little memory to even run k8s core services. Option is to have 3 static nodes (minimum for k8s anyway) of size `n1-standard-1` and then have the autoscaling for separate nodepool with these micro/small machine types. But probably you'd need more of them to serve same ammount of traffic. And it is very hard to know the price upfront without trying.

**Comment by lunemec** [comment]
Okay, I tried their calculator and the results are:
```
3x n1-standard-1 (k8s + what fits) = 145$/mo
```
And then auto-scaled using different nodes, but trying to have same ammount of memory (cpus seem the same) and running only 12h per day (peaks):
```
1x n1-standard-1 (3.75GB) = 52$/mo
2x g1-small (2x1.7GB) = 54$/mo
6x f1-micro (6x0.6) = 51$/mo
```

Seems the price is more/less the same. But maybe incrementing by smaller+cheaper nodes is better and more granular (which may end up cheaper in the end). But it depends if the Python app will have enough memory 600MB (k8s also eats up some part).

**Comment by lunemec** [comment]
I also noticed: `disk_size_gb    = 100`, that is 4 $/mo.

**Comment by hnykda** [comment]
Thanks for quick calculations. It seems valid, therefore I wouldn't invest much more in it.

Here is a screenshot of the current billing:
![image](https://user-images.githubusercontent.com/2741256/78065428-924b0c00-7393-11ea-9af2-c3c93e295f3c.png)
the last day spike is because I changed preemptible->nonpreemptible to avoid outages we had when GKE loadbalancer is slow to take off replicas out of the pool :-/ ... Let's see what it does in 14 days.

**Comment by hnykda** [comment]
![image](https://user-images.githubusercontent.com/2741256/78930949-43912680-7aa5-11ea-9901-2614b4449c3b.png)

As we switched to non-preemptible nodes, we will ran out of cash in ~2 months. So I asked google and let's see :shrug:

**Comment by hnykda** [comment]
Got an email that they may get back in ~week.

**Comment by hnykda** [comment]
Still nothing :-(

**Comment by hnykda** [comment]
:disappointed: 
![image](https://user-images.githubusercontent.com/2741256/82587694-edca9680-9b99-11ea-9bcd-eec1b9baf18f.png)
