### ISSUE TITLE
Extend countries to include Myanmar

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#348]
This is currently not among the countries we display.

**Comment by hnykda** [comment]
I believe we need to add it in the model than. @gavento do you have any ETA or can you delegate that to someone?

**Comment by hnykda** [comment]
@gavento Can you update on this? Can we model Maynmar too?

**Comment by hnykda** [comment]
@jk3141 @lagerros if we want it, we need estimates for it as per Tomas' comment https://epidemicforecasting.slack.com/archives/CV93A58G7/p1587154923185000?thread_ts=1587153769.184700&cid=CV93A58G7.

**Comment by hnykda** [comment]
https://epidemicforecasting.slack.com/archives/CV93A58G7/p1587244550196000?thread_ts=1587153769.184700&cid=CV93A58G7
