### ISSUE TITLE
Update web JSON to v4

### ISSUE THREAD

**Issue by gavento** [epidemics/covid#350]
With impending pipeline change, the JSON spec will be updated to v4.

Please prepare this in a branch, do not merge yet.

Changes:

* The region keys are ISO codes
  * `US` for countries, `US-CA` for provinces (ISO3166-2), others TBD
* Every region has
  * `data` - dictionary of any attributes embedded in the main JSON
  * `data_url` - relative URL to the main JSON file with any larger data to be loaded when the country is displayed. The file contains a single dictionary with items to be added to `data`. (Currently this is done only for one key - the graph. This is more flexible)
* Every country has all the attributes specified in `Region` [here](https://github.com/epidemics/epimodel/blob/6b83fc29b49a170bfb3ef06f0563e977ed3d14b2/epimodel/regions.py#L88).
  * For consistency, all country attributes will be CamelCase.
  * The Continent/Country/... attributes are always filled for anything below that level (in the spirit of [Tidy Data](https://www.wikiwand.com/en/Tidy_data)), e.g. a US state also has `CountryCode` and `CountryISOa3Code`. See `Level` to check the region type.

There will likely be few more (minor) changes to the structure of the known `data` items. TBA.

**Comment by gavento** [comment]
Example file:
```json
{
  "created": "2020-04-04T01:42:50.784824+00:00",
  "created_by": "gavento@chiru",
  "comment": null,
  "regions": {
    "US-CA": {
      "data": {},
      "data_url": "export-2020-04-04T01-48-25.824219+00-00/extdata-US-CA.json",
      "Name": "California, US",
      "Population": null,
      "Lat": null,
      "Lon": null,
      "OfficialName": "California",
      "Level": "subdivision",
      "M49Code": null,
      "ContinentCode": null,
      "SubregionCode": null,
      "CountryCode": "US",
      "CountryCodeISOa3": null,
      "SubdivisionCode": null
    }
  }
}
```
(We will have more data fields)

**Comment by mathijshenquet** [comment]
@gavento are you aware of the UN/LOCODE standard for cities?

https://www.unece.org/cefact/locode/service/location

There you can go to the city codes per country, e.g https://service.unece.org/trade/locode/gb.htm

**Comment by mathijshenquet** [comment]
@gavento could I also request that we add timezones to the region data. This would then be used to determine which location to show in the frontend. I could work on adding this myself.

[zone.csv.txt](https://github.com/epidemics/covid/files/4431218/zone.csv.txt)

**Comment by hnykda** [comment]
Ha, good point with the UN/LOCODE. I found a good dataset here: https://datahub.io/core/un-locode
![image](https://user-images.githubusercontent.com/2741256/78456334-5372ca00-76a3-11ea-8b65-fc74c557c9be.png)

seems to have all codes we would need. I found adding a timezone easy via https://pypi.org/project/timezonefinder/ from lat/lon in the past.

**Comment by gavento** [comment]
Thanks for pointing out UN/LOCODE db, however I am not sure how would we use it - we are on the resolution of provinces/states in SOME countries, and I don't see us having finer data anytime soon. (And when we have them, I am afraid it may be in a very different hierarchy than LOCODE, e.g. GLEAM uses something exotic that has very different resolution.)

**Comment by gavento** [comment]
Timezones should be doable. I am very much constrained on dev time/coordination now, however.
@mathijshenquet If you want to work on it, it would be best in the "new" pipeline (epimodel). Web export is not finished yet, but the groundwork is there and if you want, any help there is welcome!

**Comment by gavento** [comment]
@mathijshenquet By the way, the csv file you shared is directly useful in epimodel, thanks!
Would you please update it to have just `Code` (ISOalpha2, sorted) and `Timezone` columns, and submit it to epimodel-covid-data repo? Then inclusion in web will be almost trivial (similarly for other similar data)

**Comment by hnykda** [comment]
Additional stuff from slack:
> Someone to update the frontend a bit (change: one JSON per country for all big data, not just one graph, but otherwise just subset of "data" in a different file)

> Finding someone to update frontend to v4 JSON with minor changes (loading data from per-country file to different loc in data) + Possibly different/common time series format rather that Plotly traces? (easy-ish in pipeline, but need to know). @Daniel Hnyk could you help me find someone with the knowledge and ~2h of time tomorrow?

**Comment by hnykda** [comment]
Done in https://github.com/epidemics/epimodel/pull/25, will create follow up cards for what's left
