### ISSUE TITLE
Add R0 estimate to traces data

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#357]
If we had (maybe we do?) a good way of estimating R0 of each of the mitigation strength in the data pipeline already, we could probably display a better information (~e.g. country specific) then a hardcoded set of ones as we have it now.

[Related discussion](https://epidemicforecasting.slack.com/archives/C010LQAGCBC/p1585994052055300?thread_ts=1585868446.053000&cid=C010LQAGCBC):
> Well the problem is this isn't in any way connected to the real model, but an "UI feature" trying to illustrate things in easy to understand way - which are easy to understand and easy to mislead. R0 is not the same as R effective, when the model uses some seasonality, Reff is lower than R0, when part of the population allready recovered, Reff is loer than R0 & more.

This would be needed if we wanted to do the [Mitigation calculator](https://docs.google.com/document/d/1uwIQjNyl5oJKFuCNr79DACwfVBMM2hP3KcrGDkzYLCk/edit#heading=h.6enhpqmky8h)

**Comment by hazarane** [comment]
will be covered in #457
