### ISSUE TITLE
optimize deployment strategy

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#36]
Currently, pushing to staging and production can be done independently (e.g. you can deploy something to production without first testing on staging). Is it OK?

Maybe if we removed the "build and push" step from the production pipeline, we would know that it can be deployed without first having it in staging.

Check with devs.

**Comment by lunemec** [comment]
I think this is not super necessary. Should be done once someone actually breaks production.

**Comment by mathijshenquet** [comment]
Given recent events I suggest we add a `production` branch and replace the github action hook for deploying to production from `master` to `production`. This also frees up `master` for quicker development. We could also drop the `staging` branch and deploy staging from the `master` branch but I think having `staging` for experiments is more valuable. ping @hnykda

**Comment by mathijshenquet** [comment]
We decided against this
