### ISSUE TITLE
Namibia (NA) does not have Johns Hopkins reports in data-v4

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#381]

**Comment by hnykda** [comment]
Which is weird as it is present in https://raw.githubusercontent.com/epidemics/epimodel-covid-data/master/johns-hopkins.csv and it's [here](https://github.com/epidemics/epimodel/blob/master/config.yaml).

I suspect that because it's code is `NA`, pandas treat it as NaN

**Comment by hnykda** [comment]
https://github.com/epidemics/epimodel/commit/31a9c0305a86f5e660655fc0ef3a0551894f8b15
