### ISSUE TITLE
Missing Foretold estimates/extrapolation

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#383]
We used to have FT_estimates for many countries in v3, in v4 we only have Fortold estimates for few. Now we are using some cludge to estimate the current infected from reported data in the frontend.

We either have to:
1. Recreate estimates in the backend 
2. Properly vet the cludge so to ensure its not wrong.

**Comment by hnykda** [comment]
Fixed, was a problem with using foretold estimates instead of the Jan's table
