### ISSUE TITLE
design automating model computation

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#39]
Instead of manually triggering the gleamviz computation, could we automate it? Design it and do some cards to implement it. Is it even possible with gleamviz?

related: #9

**Comment by gavento** [comment]
No, we communicated with the Gleam side and the best they can do is give us higher limit for parallel runs, but we need to run them in GUI.

As a minor fix, I implemented a way to auto-import and auto-export the data from GleamViz:
* to Gleamviz: https://github.com/epidemics/epifor/commit/7cff764184658d32dd7e0528d1e7d061a0f95c37
* from GleamViz: Pass the *.gvh5 dirs to https://github.com/epidemics/epifor/blob/master/process_h5s.py
