### ISSUE TITLE
Custom client site (frontend side)

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#391]
Tracks the points from #389
- [ ] 1. Active infections estimates in a table (I propose we move this back, sounds like a bigger feature).
- [x] 2. Active infection estimates (just missing US)
- [x] 3. Cummulative + peak estimates 
- [x] 4. Disable/enable scenario's and custom descriptions
- [x] 5. Custom description for models, should be supplied as a HTML fragment (see below).

For 4-5 these are given on `extdata-CODE.json` as specified in
- Scenarios: https://github.com/epidemics/covid/blob/v4/common/spec/v4.ts#L62-L66
- Description: https://github.com/epidemics/covid/blob/v4/common/spec/v4.ts#L72

**Comment by hnykda** [comment]
(I will try to discuss as much as possible on #389 not to trash the discussion too much)

**Comment by mathijshenquet** [comment]
I had in mind that 'id' is the identifier in the traces i.e None, 'name' is the button name and 'description' is the text below.

**Comment by hnykda** [comment]
Moving to backlog as it's unclear we want it

**Comment by mathijshenquet** [comment]
The points 2-5 are implemented and used in production for the Pakistan website so I will close this issue. For point 1 a new issue can be opened.
