### ISSUE TITLE
Monaco missing population

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#392]
Monaco is missing population in the batch file

**Comment by hnykda** [comment]
I checked the https://github.com/epidemics/epimodel-covid-data/blob/master/regions.csv from where the populations are fetched and it's present for Monaco, so have no idea where it's getting lost.

![image](https://user-images.githubusercontent.com/2741256/79643110-9b184c00-81a1-11ea-8614-0ef271988d43.png)

**Comment by jez4** [comment]
I just ran poetry run `./do -C config-local.yaml web_export out/batch-0417.hdf data/sources/estimates-JK-2020-04-15.csv` and the generated data-CHANNEL-v4.json has the population of Monaco at 38964 . I had the fresh clone from GH . 
Are the populations taken from there ?

**Comment by hnykda** [comment]
Yes, they would be there. Therefore it's maybe fixed by something else :shrug: ?

**Comment by hnykda** [comment]
I confirm that I see it there too now! Thanks Michal for finding out then, please close this issue.

**Comment by jez4** [comment]
Was the error really in the batch file? . as I see on the pages that Monaco is not updating the population number.

**Comment by mathijshenquet** [comment]
Sorry I think I know what happend here. It was still taking the population from the UN data thing because the population field used to be broken. Sorry for the confusion.
