### ISSUE TITLE
cleanup v3

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#403]
With #401, we migrated to V4 data spec and v3 is not needed.

- [x] remove all references to v3 in the covid repo
- [x] remove all references to v3 in the epimodel repo (https://github.com/epidemics/epimodel/blob/c909fd0b849fa33e1133ac0ab9e7ed7a2a0f0af7/config.yaml#L22)
- [x] delete old data from GCS to save space

**Comment by mathijshenquet** [comment]
I think we can do this now

**Comment by mathijshenquet** [comment]
#437 fixes this for the frontend

**Comment by hnykda** [comment]
@mathijshenquet Can I delete the old files from GCS? :-)

**Comment by mathijshenquet** [comment]
Yep!

**Comment by hnykda** [comment]
Skimming through the loaded resources, I see there is still v3 loaded on the main page:
![image](https://user-images.githubusercontent.com/2741256/81396073-0318dd00-9125-11ea-8559-ff34ec78ac1b.png).

Other than that, it seems that the latest generated file is from April 17.
![image](https://user-images.githubusercontent.com/2741256/81396160-2cd20400-9125-11ea-8565-1eed5808032b.png)

Balochistan is probably: `gs://static-covid/static/data-balochistan-v4.json` and that ones uses `2020-05-04T02:50:54.174593+00:00`. @lagerros can you confirm please that this is the correct balochistan file?

**Comment by mathijshenquet** [comment]
I cannot reproduce loading `data-main-v3.json` is that just epidemicforecasting.org/?

**Comment by hnykda** [comment]
(dealt with via slack)

**Comment by mathijshenquet** [comment]
This has been fixed by https://github.com/epidemics/covid/commit/6f31e7ca3f8045bef69949ce77b59329383e4a2b

**Comment by hnykda** [comment]
I deleted what was possible, we are on only 350MB in the bucket, so negligible  :+1: .
