### ISSUE TITLE
Generate gleamviz xml files from output csv in Ought colab notebook

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#406]
[This notebook](https://colab.research.google.com/drive/1ZtXF95N2cKNS7XfcSz4dwRWkTgKi4Vmw) outputs both estimates of active infections and a list of gleam exceptions. Both are easily specified using a combination of Foretold and spreadsheets.

I'd want us to integrate the output with our existing libraries (in epimodel? or epifor?) for generating gleam files. 

The current situation seems like: 
- Tomas has some know-how for and some really neat scripts
- But they are not documented 
- They require a fair bit of local set-up
- It's hard to onboard new people on the modelling team to use them 

What I want is: 
- Someone from the pro bono modelling team, or even a different research group altogether, can just spin up the colab notebook, and with the press of a button generate the corresponding gleam files. No need for separate python scripts or installing additional local software

This would make a massive difference to our ability to do custom modelling work.

So this requires integrating our libraries in that notebook.

**Comment by hnykda** [comment]
This is a bigger task. 

To make it actually useful, it would need much more design upfront, like how to deal with parameters for gleam (AFAIK we rather use some subset), how we combine strategies and groups and so on. Not sure how much more generic we can go, that really depends on Tomas though, he sees inside this.

I am also not that sure that having everything integrated in a notebook is the best solution compared to better documenting our library and making it more reusable. It needs a lot of specific data.

**Comment by lagerros** [comment]
More detailed spec can be found here https://docs.google.com/document/d/1CJmoL0ypDTKjtpVLdyVTajeqKRp4HKujEduavkwobl8/edit?usp=drivesdk

That will probably clarify some things. 

Could @gavento let me know if/when your are able to take this on?

**Comment by gavento** [comment]
Here is a version with most relevant exception adding features:
https://colab.research.google.com/drive/1X0Z8ola2wm0ur_kyeIBYDaAJy_XSNOC_

I also added a rather detailed description of the steps to use it, and some more notes.

Note that I had to change the spreadsheet example link (there were errors, e.g. "Sau Paulo") but the semantics are the same. The new spreadsheet is [here](https://docs.google.com/spreadsheets/d/1xY2eZd9I_YcmWl1KgssV8iWePATp2QlWUhjNBUhRKdI/edit#gid=0
) and has some notes and examples.

Feature: The "Classes" can be any strings as long as they match exactly. This will create the sim name.
Feature: Has optional beta-multiplier parameter to generate more scenarios
Feature: Either "background" or "packages" may be non-present.
Feature: The regions may be specified by codes as well (e.g. in name conflicts).
Feature: Lines with empty Region are ignored in the sheet

@lagerros

**Comment by gavento** [comment]
Note that the code is quite easily modifiabe and hackable - there is no Gleam complexity in this (and I believe others could also have built this with a bit of background knowledge, or improved further).

**Comment by gavento** [comment]
TODO: Check how exceptions in gleam take priority (hierarchy? or just order? how?)
Note: The exceptions in the Colab are added first background then package. Adding a "Priority" column is possible (but likely feature bloat ATM).

**Comment by lagerros** [comment]
Fantastic, looking forward to taking a look. For some reason can't open it though: 
![image](https://user-images.githubusercontent.com/21347592/79920839-e753ce00-83e5-11ea-929e-aa504e279689.png)

**Comment by gavento** [comment]
Note there is now an updated version that also updates XML wit population estimates: https://colab.research.google.com/drive/1-OLs0Cp8znvyj-ku9X0gJbBBh9bYpu2q#scrollTo=RoudoaT3FgTb

**Comment by gavento** [comment]
The "Ought" and this colab are compatible - just pass the output CSV from the first into this.
Detailed inspection of the estimates is needed anyway, and this split endorses it. 
Actual merge seems to be low priority and additional value, closing for now.
