### ISSUE TITLE
unify usage of initial_df and estimates_df

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#409]
Currently we source this from two places in the export:

* from https://github.com/epidemics/epimodel/blob/83f9bdd33a567d97b3b28904ac9fdef95a0831ab/epimodel/exports/epidemics_org.py#L453
* from the additional estimates sheet: https://github.com/epidemics/epimodel/blob/83f9bdd33a567d97b3b28904ac9fdef95a0831ab/epimodel/exports/epidemics_org.py#L499

I guess the motivation is to use the former for setting the correct y-axis offset of the trace and the latter to have fresh data for estimates, so both may be valid.

**Comment by mathijshenquet** [comment]
`initial_df` is/will be removed in the epimodel PR created during the Pakistan push

**Comment by mathijshenquet** [comment]
This has been resolved
