### ISSUE TITLE
Add disclaimer to website

### ISSUE THREAD

**Issue by Nora-Ammann** [epidemics/covid#413]
Disclaimer:

> - This work is produced on a pro-bono, good faith basis. Although many of the staff and volunteers of the EpidemicForecasting.org project have relevant professional experience, it is not professional or medical advice
> - While every reasonable effort has been made to ensure that the information is correct, the views expressed are accurate and represent the best available evidence, and all reasonable care has been taken in the production of modelling, no responsibility or liability is accepted for errors or omission of fact or for any opinions expressed herein, or any decisions which any party make while relying in whole or in part on this document
> - Readers and users of our work are advised to form their own independent judgement with respect to any matter contained in this document
> - The global knowledge base on COVID-19 is changing rapidly. Facts, opinions, projections, and estimates are subject to change without notice. Readers and users of our work are advised to avoid using modelling outputs which are not very recent when making public policy decisions
> - This work is produced by staff and volunteers from a range of organisations. It is the work of the authors as individuals, not as institutions. None of the University of Oxford, the Future of Humanity Institute, Australian National University or any other organisation accept responsibility or liability for this work

**Comment by mathijshenquet** [comment]
Nora could you check that it is ok like this? The disclaimer is visible after pressing the disclaimer button in the footer. I also removed the line `As of March 28, this is a beta, and while it runs on real data it will be a few days until it is properly vetted`
