### ISSUE TITLE
Improve `web_export` and `web_upload` ergonomics

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#415]
I think exporting the data is a bit to fiddly and these things would really streamline my workflow: 
1. Copy latest exports to `out/latest`, 
2. Make `./do web_export` output a formatted JSON which is then verified and 'minified' by `./do web_upload`. 
3. Make it so that `./do web_upload` uploads the latest thing you generated by default.

**Comment by mathijshenquet** [comment]
@gavento could you give your opinion on these ideas, we could do it together with https://github.com/epidemics/covid/issues/394

**Comment by mathijshenquet** [comment]
4. Add a `--upload CHANNEL` flag or something similar to `./do web_export` which also runs `./do web_upload` after

**Comment by gavento** [comment]
@mathijshenquet I like all of them!

**Comment by eohomegrownapps** [comment]
@mathijshenquet would you find it more convenient / would it be better for 1) and 2) to be optional?

**Comment by mathijshenquet** [comment]
Hey @eohomegrownapps, I think its good if both would be default behavior unless you know some reason why it would be undesirable. I expect copying the files to be very quick and uploading the files by hand is not a normal workflow. Its probably good if 2 had a flag to disable it.

**Comment by eohomegrownapps** [comment]
@mathijshenquet I've made 1) default. I assumed that viewing the JSON files before uploading them was not in the normal workflow so made 2) not default -- I could change this if that would be better (or alternatively I could make it only prettify the files in the latest/ directory, so as to avoid lots of large export directories).

**Comment by mathijshenquet** [comment]
Does it make a very big difference in file size? In any case and I'm also fine with 2 being behind a flag by default. Prettifying only the files in `latest/` is not completely helpful as I often wanted to compare the latest output with a previous output. I trust your judgement.

**Comment by eohomegrownapps** [comment]
@mathijshenquet 
> Prettifying only the files in latest/ is not completely helpful as I often wanted to compare the latest output with a previous output.

Ah, in that case I'll leave it as-is.

> Does it make a very big difference in file size? 

(Using the sample HDF I was given) it increases the file size of `data-CHANNEL-v4.json` by ~5x (from ~0.6MB to ~2.5MB), and the file size of the region JSONs by ~2x (from ~0.5MB to ~1.1MB).

A few other things that might be relevant:
- Currently (because gsutil takes as input a path to a directory) I overwrite all the pretty-printed files in the directory to be exported with their minified versions -- if you have to compare the latest output with a previous output, I assume it might then be better to have the export minification and upload taking place in a separate directory? In that case, is it important what the google storage URL of the uploaded folder is? (e.g. `gs://static-covid/static/export-2020-04-29T18-58-57.021510+00-00`)

**Comment by mathijshenquet** [comment]
I don't think the folder name is important, the `data-{CHANNEL}-v4.json` files in the root are the only reference we have into those folders. 

I thought it about it a bit more and I think this is the best solution:

1) The generated files to `out/` stay as they are now except that they are pretty printed.
2) The uploaded web for $CHANNEL files go minified to `gs:://static-covid/static/$VERSION/$CHANNEL/` (so uploading to production would go to  `gs:://static-covid/static/v4/main`), the version can be hard coded for now.
2b) Rename `data-CHANNEL-v4.json` -> `data-v4.json` everywhere. I never liked the the special processing of this.

This prevents the exports from accruing in gbucket over time as it should not serve (and currently does not serve) as a backup. This way `web_export export-2020-...` can just create a `$CHANNEL/` dir (in `out/` should be fine) where it minifies the content of `export-2020-...` and then uploads it with `gsutil`.

This would require a change on the frontend as well but I can do that very easily.

WDYT @eohomegrownapps @gavento @hnykda ?

**Comment by hnykda** [comment]
I am fine with the proposal, sounds good.

Personally I would get rid of any prettyprinting - get a decent editor or [some browser extension](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh) :grin:

**Comment by eohomegrownapps** [comment]
@mathijshenquet sounds good :) (n.b. someone will need to test the upload-to-gs functionality as I'm not able to do so)

@hnykda for convenience, I'll keep pretty-printing as an option that's not enabled by default (and web_upload will automatically minify all JSON files before uploading them).

**Comment by eohomegrownapps** [comment]
Quick ergonomics poll -- @lagerros (and others), if we end up adding more workflows like the one you were thinking about, might it be neater to rework the commands as follows:

- An `action` command group (e.g. `./do action update-foretold`) which would allow for command chaining (e.g. `./do action web-export batch.hdf5 estimates.csv web-upload --channel main`) 
- A `workflow` command group (`./do workflow prepare-gleam`) that should be easily extensible for people to add their own workflow macros (perhaps this might even read from a script that's not tracked by git).

But apart from that I think everything's now been sorted :)

**Comment by lagerros** [comment]
`Workflow` could be usable, but no strong preference.

Have you PR:ed the other changes? Could you document what new commands are now available? :)

**Comment by eohomegrownapps** [comment]
@lagerros in that case I'll go for the `action` / `workflow` split (makes life a lot easier with command chaining)

My changes are currently in upstream/cli-refactoring -- I'll make a PR once I've done some documentation :)

(Speaking of documentation, would it be a good idea to add the sphinx / readthedocs setup, or should I leave that for a separate PR?)

**Comment by lagerros** [comment]
I haven't seen the sphinx thing, could you link me? 

Probably do it in a separate PR though.

**Comment by hnykda** [comment]
Sphinx is a tool generating documentation. I am skeptical of the benefits of having sphinx documentation btw. I don't think it would be worthy.

**Comment by eohomegrownapps** [comment]
I agree there's little point in having much documentation for the codebase itself (as it's still changing rapidly)... I was thinking it might be useful to have some documentation for tools (like `do`) and for some of the datasets used, but I guess this is probably already on Notion

**Comment by lagerros** [comment]
No, it's not all on Notion -- but if you wanted to add it there, that could be very useful!

**Comment by eohomegrownapps** [comment]
@lagerros Everything (including docstrings) should now be finished in upstream/cli-refactoring if you want to have a look / test -- there are a few commands (things involving gleam batches) I haven't been able to test satisfactorily on my machine, so there is a small chance of bugs... I'll write up a PR properly for this tomorrow.

**Comment by AcesoUnderGlass** [comment]
is there a reason you don't want create-and-upload to be one step?

**Comment by eohomegrownapps** [comment]
@AcesoUnderGlass do you mean `web-export` and `web-upload`? From what I've gathered @mathijshenquet wants to be able to perform `web-export` first, debug / analyse the JSONs then `web-upload` them afterwards (#415). If you want to do them all in one step, command chaining should work (so you could run e.g. `./do action web-export out/batch.hdf5 data/sources/estimates.csv web-upload -c main`)

**Comment by mathijshenquet** [comment]
Yeah this is correct.
