### ISSUE TITLE
move source data for mitigation map to epimodel

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#419]
Currently, the data are being fetched from https://storage.googleapis.com/static-covid/static/beta-estimates-2020-04-20.csv. We should at least commit it into epimodel-data repository.

We should incorporate it into either a separate file or into the main JSON.

I am not sure how often these will change though, so I do not think it is worth it. Let us keep an eye on that and depending on how often these change, we can incorporate it. 

cc @veselyvojtech

**Comment by mathijshenquet** [comment]
There is a commit in `epimodel/no-initial` (should be cherry picked) which adds `Beta1` and `Beta2` to the `data.csv`. This is already put into the `model` on the frontend. @jez4 could you quickly confirm which of those you are using, or is it something else entirely? See here: https://storage.googleapis.com/static-covid/static/data-testing-v4.json `regions[].CurrentEstimate`. I can wire it up with the frontend after.

**Comment by jez4** [comment]
@mathijshenquet I am sorry but I do not know how to help with this. I am not using any of these.

**Comment by hnykda** [comment]
It was @veselyvojtech working on this. Vojta, can you answer Mathijs please?

**Comment by mathijshenquet** [comment]
Whoops, sorry Michal

**Comment by hnykda** [comment]
@veselyvojtech any chance you could do this?

**Comment by hnykda** [comment]
Moving to backlog, it's not priority.

**Comment by witzatom** [comment]
i think that this has been closed by https://github.com/epidemics/epimodel/pull/65
