### ISSUE TITLE
Fail gracefully if too few scenarios are submitted 

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#422]
Currently if I submit traces that cover 8 different scenarios, but "Groups" in config only specify 4 scenarios; the website displays nothing at all. 

It would be better if it just defaulted to the four scenarios it found. 

Relevant code snippet, as spotted by Tomas in the dev console. It fails on `undefined` in

`    objs.forEach((scenario: Scenario) => {
      function readStat(obj: v4.ScenarioStats, key: string): Stat {
        let stat = obj[key];
        if (!stat) console.error(`Missing stat ${obj}:${key}`, obj);
        return stat;
      }`

**Comment by mathijshenquet** [comment]
https://github.com/epidemics/covid/blob/0e04bb3c046618b60ab9e9e0ac6b77951136a9d5/frontend/models/scenario.ts#L57

**Comment by mathijshenquet** [comment]
@Jacob I pushed a potential fix to this. Because this issue was not reproducible I'm not really sure why it was failing.

If it does not work please reopen this issue and push the data to a specific channel like `bug-422` so I can easily reproduce it.
