### ISSUE TITLE
Round large y-axis to no decimals

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#430]
The new cumulative graph ("total") feature is really nice. 

Would it be possible for the y-axis to round to no significant digits for larger numbers?
i.e. could it say “70%” instead of “70.0%“?

We'd still want it such that if you zoom in on smaller numbers (e.g. the 0%-1% range) it show more decimals.  

Not sure how hard this is; probably not worth it if it's messy, but would be nice if it's easy. 

![image](https://user-images.githubusercontent.com/21347592/80538728-107edc00-895b-11ea-82e4-74e98d034446.png)

**Comment by danuluma** [comment]
![Screenshot_2020-05-02 Medium-Term COVID-19 Forecast(1)](https://user-images.githubusercontent.com/35179392/80855123-f8eb7000-8c46-11ea-9913-60548ad9e56a.png)
![Screenshot_2020-05-02 Medium-Term COVID-19 Forecast](https://user-images.githubusercontent.com/35179392/80855124-fab53380-8c46-11ea-87af-209363bcd50c.png)

Hi @lagerros how does this look
