### ISSUE TITLE
Problems in `countermeasure-tags.csv`

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#436]
- [ ] School closure category should be `sum unique`
- [ ] There is a problem with `Diagnostic criteria loosened` and `Diagnostic criteria tightened` because the `description` field in notion is not the expected format.

**Comment by wolverdude** [comment]
@mathijshenquet These CSVs are exported directly from Notion. If there's an issue, fix it in notion. These are currently out of date, but I can have them updated regularly whenever there's a need for it.

**Comment by mathijshenquet** [comment]
What code are you using for it?

**Comment by wolverdude** [comment]
* [export-countermeasure-tags.ipynb](https://github.com/epidemics/containment/blob/wolverdude/frontend/export-countermeasure-tags.ipynb)
* [export-countermeasures.ipynb](https://github.com/epidemics/containment/blob/wolverdude/frontend/export-countermeasures.ipynb)

I really should refactor those into a single collab.

**Comment by hnykda** [comment]
Is this a hard blocker for countermeasures release, or nice to have?

**Comment by hazarane** [comment]
Outdated, replaced by #461 #477 , if there will be some issues with new export we'll add new tickets.
