### ISSUE TITLE
Prepare frontend for data location change

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#439]
Related to@mathijshenquet thanks for making this PR :)

From https://github.com/epidemics/epimodel/pull/50:

> The uploaded `$CHANNEL` files are now stored at `gs:://static-covid/static/$VERSION/$CHANNEL/` (so uploading to production would go to `gs:://static-covid/static/v4/main`). 
> 
> **This will require changes in the front-end.**

**Comment by hnykda** [comment]
Moving to ToDo as the dependency got merged.

**Comment by hnykda** [comment]
But there is another blocker - balochistan data: https://epidemicforecasting.slack.com/archives/C0100EK7N8N/p1589142763374200?thread_ts=1588935374.335200&cid=C0100EK7N8N
