### ISSUE TITLE
Mitigation calculator

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#445]
Placeholder: Information about this on slack dev-general / dev-data channels.

Todo:
- [ ] Ensure it works on edge, specifically the slider CSS  ms- attributes
- [x] Coordinate with Jan Kulveit on updated numbers from #countermeasures-modelling 
- [x] Check and polish copy, feedback on UI
- [x] Convert growth impact to percentages
- [x] Clip serial interval internally away from 0

**Comment by hnykda** [comment]
:clap:
