### ISSUE TITLE
integrate  `.do` script as part  of the epimodel lib

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#450]
Currently, epimodel is triggered by the [do](https://github.com/epidemics/epimodel/blob/master/do) script. It could be part of a `epimodel/__main__.py` so it's possible to run it as a module  e.g. `python -m epimodel` or when installed via `install_scripts`.

**Comment by eohomegrownapps** [comment]
Click has some support / guidance for doing this: https://click.palletsprojects.com/en/7.x/setuptools/

**Comment by hnykda** [comment]
thanks

**Comment by hnykda** [comment]
Closed by https://github.com/epidemics/epimodel/pull/60/
