### ISSUE TITLE
Task: Merge `covid` and `epimodel` into one repo

### ISSUE THREAD

**Issue by mathijshenquet** [epidemics/covid#451]
# Description
The repo's `epimodel`, are all somehow coupled together. This creates the undeseriable situation that a single feature or improvement produces up as three different PR's. It also complicates project management e.g. needing to hunt down issues and PR's.

In a call with @hnykda, @AcesoUnderGlass and @wolverdude we reached consensus to merge these repo's together to improve ergonomics. As `covid` already hosts project management it is the natural candidate to become the basis of the new super repo.

# Task
This task should ideally be executed when there are no large PR's or features in development.

The proposed folder layout will be the following straightforward mapping. Possible followups might move things into the root if it makes sense.
- The current `covid` repo -> `web/` subdirectory
- The current `epimodel` repo -> `data/` - the rename because the epimodel repo is mainly used to generate the web export dataset, it is not really a modelling repo

The following things will have to be done:
- Ensure that CI (Github Actions) still work
- Make the CI runs dependend which files are changed using [this feature](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths)
- Particularly important: Ensuring that the [helm deploys of `covid`](https://github.com/epidemics/covid/tree/master/deploy/chart) still work

**Comment by mathijshenquet** [comment]
@MrinankSharma seems to be another major user of `epimodel` at https://github.com/epidemics/epimodel/commits/validation-holdout (although that branch has diverged from `master` in early April).

**Comment by witzatom** [comment]
Related to the comment ^^ I think it might be a good idea to simply incoroporate the epimodel master into covid, and let the validation-holdout take over the maintenance of the epimodel repo. The current epimodel masters use case is to create web exports, while validation-holdouts main use case is presentation of the countermeasures model for the paper.

**Comment by hazarane** [comment]
UPD description: merge the epimodel repo into the covid repo. The epimodel repo will exist, but remain as a repo for countermeasures model code only (currently validation-holdout branch).
