### ISSUE TITLE
The jinja function url_for is not used everywhere for paths

### ISSUE THREAD

**Issue by Bachibouzouk** [epidemics/covid#76]
This is a "nice-to-have" with lower priority

Example 
`<link href="../static/css/main.css" rel="stylesheet" />`
would become
`<link href="{{ url_for('static', path='/css/main.css') }} rel="stylesheet" />`

If you want the url of a view you can simply use `url_for(<name of the view>)`

**Comment by hnykda** [comment]
Fixed #98
