### ISSUE TITLE
For each country-specific view (view 1), display text of containment measures from containment measures database

### ISSUE THREAD

**Issue by lagerros** [epidemics/covid#78]
The measures for each location can be found in this database: https://www.notion.so/977d5e5be0434bf996704ec361ad621d?v=aa8e0c75520a479ea48f56cb4c289b7e

Not yet implemented: parser from notion to pandas or csv

```
import os
import keyring


from notion.client import NotionClient

# Obtain the `token_v2` value by inspecting your browser cookies on a logged-in session on Notion.so
# I used keyring to save the token locally
token_v2 = keyring.get_password("notion", "token")
client = NotionClient(token_v2=token_v2)

cv = client.get_collection_view(
    "https://www.notion.so/977d5e5be0434bf996704ec361ad621d?v"
    "=aa8e0c75520a479ea48f56cb4c289b7e"
)
# here are the fields which interest us
# Country
# Description of measure implemented
# Keywords
# Source


# Run a filtered/sorted query using a view's default parameters
result = cv.default_query().execute()
for row in result:
    print(row.description_of_measure_implemented)
```

The containment measures could be in the sidebar with similar design as the previous one (one entry for each date, descending)

**Comment by Bachibouzouk** [comment]
To which view name in `main.py` does view 1 corresponds?

**Comment by lagerros** [comment]
http://epidemicforecasting.org/model

`@app.get("/model")`

**Comment by lagerros** [comment]
If you want to take this on @Bachibouzouk feel free to assign yourself to it

**Comment by Bachibouzouk** [comment]
> If you want to take this on @Bachibouzouk feel free to assign yourself to it

I will work on #52 first, then I'll see if it is still free :)

**Comment by lagerros** [comment]
Excellent, just checking you've seen this, which contains the most update calculations to be made? https://www.notion.so/Modelling-d5e0bdaf1733416981ad12c78c69e7d3

**Comment by Bachibouzouk** [comment]
> Excellent, just checking you've seen this, which contains the most update calculations to be made? https://www.notion.so/Modelling-d5e0bdaf1733416981ad12c78c69e7d3

Yes I was merging the conflicts from the `risk` branch of #52 and then I was about to start reading this document. Have you seen my question [there](https://github.com/epidemics/covid/issues/11#issuecomment-599228279)?
