### ISSUE TITLE
view 1 - visualize model with CI intervals per area

### ISSUE THREAD

**Issue by hnykda** [epidemics/covid#8]
Based on Jan Kulveit's [description in slack](https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1583621745001600) (also [this](https://epidemicforecasting.slack.com/archives/CV1F9NB5K/p1583684215018500?thread_ts=1583675141.016900&cid=CV1F9NB5K)). 

### Selection
User should be able to select the following parameters:
* `area`: a selection from countries and cities (not hemispheres, regions...)
* `reduction transmission due countermeasures` - 0%, 25%, 50%, 75%

User selects e.g. 25%, and then we display 4 (or up to 8) different (gleamviz-precomputed) timeseries with different additional gleamviz parameters (e.g. seasonality).

The motivation for multiple trajectories is to visualize the uncertainty (a tooltip "Why multiple lines?" with an explanation may be helpful).

Data will be provided by Jan.

Open questions:
* we can select just some specific main cities/locations, e.g. we don't have data for Africa [Jan does it]

### Technical
* `x-axis`: "timestep", start-date is in the `definition.xml` (+ we should somewhere note the date of the model generation, e.g. in a tooltip)
* the central line glyph displays `median` column for the given area
* band glyph is shown for lower and upper CI around the central line glyph
  * we don't want to visualize the 95% CI intervals from the file! These are CIs for stochastic uncertainty of the model generation, not the uncertainty from the parameters (i.e. seasonality). For MVP, we just show the "medians" - lines, we can think about showing this uncertainty better in the future (e.g. shifting those medians back and forth by few days or by fitting some "average" from all four/eight models)
* hover tool which displays relevant values for a given position. I believe we should just show the value of each line.

## AC
* the chart corresponding to the spec is accessible via the website

**Comment by hnykda** [comment]
@hrosspet Are you willing to work on this one, primarily?

**Comment by hrosspet** [comment]
Yes. It looks like there is currently nothing better for me to do :)

**Comment by hnykda** [comment]
If you accidentally find something useful about the data spec, please put them to comments under #12 , it would be great to help someone who's gonna work on this.

**Comment by hnykda** [comment]
@hrosspet Updated. Main points:

1. for MVP, we don't want the bands, especially not the ones from the files themselves. We really just want a line for the "Median".
2. we'll display 4 or 8 of these medians (we'll have like 8 files for each parameter-selection) in one plot, each of these will be a different model

**Comment by hrosspet** [comment]
I just finished the visualization according to the previous specification (just the visualization, not the selection, yet). I pushed it now and will look into the changes after the lunch.

**Comment by hnykda** [comment]
closed

**Comment by hnykda** [comment]
via #23
